HEADER	#### Appendix 1 %%%%
HEADER	#### Abacavir %%%%
DRUG:	 TIPRANAVIR 
DRUG:	 ORLISTAT 
HEADER	#### Abatacept %%%%
DRUG:	 ADALIMUMAB 
DRUG:	 INFLIXIMAB 
DRUG:	 ETANERCEPT 
DRUG:	 VACCINES 
HEADER	#### Abiraterone %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
HEADER	
HEADER	#### ACE Inhibitors %%%%
DRUG:	 ALISKIREN 
DRUG:	 ANGIOTENSIN-II RECEPTOR ANTAGONISTS 
DRUG:	 BEE VENOM EXTRACTS 
DRUG:	 CICLOSPORIN 
DRUG:	 EVEROLIMUS 
DRUG:	 POTASSIUM- SPARING DIURETICS AND ALDOSTERONE ANTAGONISTS 
DRUG:	 LITHIUM 
DRUG:	 POTASSIUM SALTS 
DRUG:	 SODIUM AUROTHIOMALATE 
DRUG:	 WASP VENOM EXTRACTS 
HEADER	#### Aciclovir %%%%
HEADER	#### Adalimumab %%%%
DRUG:	 ANAKINRA 
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Adefovir %%%%
HEADER	#### Adenosine %%%%
DRUG:	 ANTI-ARRHYTHMICS 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 BETA-BLOCKERS 
DRUG:	 DIPYRIDAMOLE  
HEADER	
HEADER	#### Adrenergic Neurone Blockers %%%%
DRUG:	 GENERAL ANAESTHETICS 
HEADER	#### Adrenergic Neurone Blockers %%%%
DRUG:	 ADRENALINE (EPINEPHRINE) 
DRUG:	 METHYLPHENIDATE 
DRUG:	 OXYMETAZOLINE 
DRUG:	 XYLOMETAZOLINE 
HEADER	
HEADER	#### Afatinib %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Agalsidase Alfa and Beta %%%%
HEADER	#### Agomelatine %%%%
DRUG:	 CIPROFLOXACIN 
DRUG:	 FLUVOXAMINE  
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
HEADER	#### Albendazole %%%%
DRUG:	 PHENOBARBITAL 
DRUG:	 PRIMIDONE 
DRUG:	 RITONAVIR 
HEADER	#### Alcohol %%%%
DRUG:	 CYCLOSERINE 
DRUG:	 COUMARINS  
DRUG:	 PHENINDIONE 
DRUG:	 TRICYCLICS 
DRUG:	 TRABECTEDIN 
DRUG:	 DAPOXETINE 
DRUG:	 PARALDEHYDE 
DRUG:	 ACITRETIN  
HEADER	#### Aldesleukin %%%%
DRUG:	 CORTICOSTEROIDS 
DRUG:	 VINBLASTINE 
HEADER	#### Alemtuzumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	
HEADER	#### Aliskiren %%%%
DRUG:	 ACE INHIBITORS 
DRUG:	 IRBESARTAN 
DRUG:	 ITRACONAZOLE 
DRUG:	 CICLOSPORIN 
DRUG:	 GRAPEFRUIT JUICE 
HEADER	
HEADER	
HEADER	#### Allopurinol %%%%
DRUG:	 DIDANOSINE  
DRUG:	 AZATHIOPRINE  
DRUG:	 MERCAPTOPURINE  
HEADER	
HEADER	
HEADER	
HEADER	#### Alpha-blockers %%%%
DRUG:	 GENERAL ANAESTHETICS 
DRUG:	 MAOIS 
DRUG:	 KETOCONAZOLE 
DRUG:	 BOCEPREVIR 
DRUG:	 TELAPREVIR 
DRUG:	 AVANAFIL 
DRUG:	 BETA-BLOCKERS 
DRUG:	 VERAPAMIL 
DRUG:	 COBICISTAT 
DRUG:	 DIURETICS 
DRUG:	 MOXISYLYTE 
DRUG:	 SILDENAFIL  
DRUG:	 DOPAMINE 
DRUG:	 TADALAFIL 
DRUG:	 TADALAFIL 
DRUG:	 RANITIDINE 
DRUG:	 VARDENAFIL 
HEADER	
HEADER	
HEADER	#### Amantadine %%%%
DRUG:	 MEMANTINE 
HEADER	#### Ambrisentan %%%%
DRUG:	 CICLOSPORIN  
HEADER	#### Aminoglycosides %%%%
DRUG:	 CAPREOMYCIN  
DRUG:	 CEPHALOSPORINS 
DRUG:	 PHENINDIONE 
DRUG:	 CICLOSPORIN 
DRUG:	 PLATINUM COMPOUNDS 
DRUG:	 LOOP DIURETICS 
DRUG:	 NON- 
DRUG:	 SUXAMETHONIUM 
DRUG:	 PYRIDOSTIGMINE 
DRUG:	 TACROLIMUS 
HEADER	#### Aminophylline %%%%
DRUG:	 QUINOLONES 
DRUG:	 PRIMIDONE  
DRUG:	 PHENYTOIN 
DRUG:	 KETOCONAZOLE 
DRUG:	 RITONAVIR  
DRUG:	 VERAPAMIL  
DRUG:	 DEFERASIROX  
DRUG:	 PEGINTERFERON ALFA  
DRUG:	 SUCRALFATE  
HEADER	
HEADER	#### Amiodarone %%%%
DRUG:	 DRONEDARONE 
HEADER	#### Amiodarone %%%%
DRUG:	 FLECAINIDE 
DRUG:	 LEVOFLOXACIN  
DRUG:	 TELITHROMYCIN 
DRUG:	 PHENINDIONE  
DRUG:	 DABIGATRAN  
DRUG:	 TRICYCLICS 
DRUG:	 PHENYTOIN  
DRUG:	 MIZOLASTINE 
DRUG:	 CHLOROQUINE 
DRUG:	 QUININE 
DRUG:	 TOLTERODINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 PIMOZIDE  
DRUG:	 ZUCLOPENTHIXOL 
DRUG:	 SULPIRIDE 
DRUG:	 SIMEPREVIR  
DRUG:	 RITONAVIR  
DRUG:	 TELAPREVIR  
DRUG:	 ATOMOXETINE 
DRUG:	 BETA- BLOCKERS 
HEADER	#### Amiodarone %%%%
DRUG:	 BETA-BLOCKERS 
DRUG:	 SOTALOL 
DRUG:	 VERAPAMIL 
DRUG:	 DIGOXIN  
DRUG:	 COBICISTAT 
DRUG:	 COLCHICINE 
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 FINGOLIMOD 
DRUG:	 IVABRADINE 
DRUG:	 SIMVASTATIN  
DRUG:	 LOMITAPIDE 
DRUG:	 LITHIUM  
DRUG:	 PENTAMIDINE ISETIONATE 
HEADER	
HEADER	#### Amphotericin %%%%
DRUG:	 CARDIAC GLYCOSIDES 
DRUG:	 CICLOSPORIN 
DRUG:	 CORTICOSTEROIDS 
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 SODIUM STIBOGLUCONATE 
DRUG:	 TACROLIMUS 
HEADER	
HEADER	#### Anabolic Steroids %%%%
DRUG:	 PHENINDIONE 
HEADER	#### Anaesthetics, General %%%%
DRUG:	 ADRENERGIC NEURONE BLOCKERS 
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 DROPERIDOL 
DRUG:	 VERAPAMIL  
DRUG:	 METHOTREXATE 
DRUG:	 LEVODOPA 
DRUG:	 DOXAPRAM  
DRUG:	 MEMANTINE  
DRUG:	 SUXAMETHONIUM 
DRUG:	 ATRACURIUM 
DRUG:	 NORADRENALINE (NOREPINEPHRINE) 
DRUG:	 METHYLPHENIDATE 
HEADER	
HEADER	
HEADER	
HEADER	#### Anagrelide %%%%
DRUG:	 CILOSTAZOL 
DRUG:	 ENOXIMONE  
DRUG:	 MILRINONE 
HEADER	#### Anakinra %%%%
DRUG:	 GOLIMUMAB  
DRUG:	 INFLIXIMAB 
DRUG:	 ETANERCEPT 
DRUG:	 VACCINES 
HEADER	
HEADER	#### Angiotensin-II Receptor Antagonists %%%%
DRUG:	 ACE INHIBITORS 
DRUG:	 ALISKIREN 
DRUG:	 CICLOSPORIN 
DRUG:	 POTASSIUM-SPARING DIURETICS AND ALDOSTERONE ANTAGONISTS 
DRUG:	 LITHIUM  
DRUG:	 POTASSIUM SALTS 
HEADER	#### Antacids %%%%
DRUG:	 ERLOTINIB 
HEADER	#### Antacids %%%%
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	#### Antidepressants, Noradrenaline Re-uptake Inhibitors  %%%%see
HEADER	#### Antidepressants, SSRI %%%%
DRUG:	 AMINOPHYLLINE  
DRUG:	 TRAMADOL 
DRUG:	 PROPAFENONE 
DRUG:	 TELITHROMYCIN 
DRUG:	 DABIGATRAN 
DRUG:	 MAOIS 
HEADER	#### Antidepressants, SSRI %%%%
DRUG:	 MOCLOBEMIDE  
DRUG:	 TRICYCLICS  
DRUG:	 ANTIEPILEPTICS  
DRUG:	 PHENYTOIN 
DRUG:	 CYPROHEPTADINE 
DRUG:	 ARTEMETHER WITH LUMEFANTRINE  
DRUG:	 QUININE 
DRUG:	 DROPERIDOL  
DRUG:	 CLOZAPINE 
DRUG:	 PERPHENAZINE  
DRUG:	 PIMOZIDE  
HEADER	#### Antidepressants, SSRI %%%%
DRUG:	 RISPERIDONE  
DRUG:	 RITONAVIR 
DRUG:	 ZOLPIDEM 
DRUG:	 PROPRANOLOL 
DRUG:	 SOTALOL  
DRUG:	 CLOPIDOGREL 
DRUG:	 DAPOXETINE  
DRUG:	 SELEGILINE  
DRUG:	 TAMOXIFEN  
DRUG:	 FROVATRIPTAN 
DRUG:	 ZOLMITRIPTAN  
DRUG:	 LITHIUM  
DRUG:	 METHYLTHIONINIUM 
DRUG:	 TIZANIDINE  
DRUG:	 PENTAMIDINE ISETIONATE  
DRUG:	 PIRFENIDONE 
DRUG:	 POMALIDOMIDE 
DRUG:	 THEOPHYLLINE  
HEADER	
HEADER	#### Antidepressants, Tricyclic %%%%
DRUG:	 ALCOHOL 
DRUG:	 OPIOID ANALGESICS 
DRUG:	 PROPAFENONE 
DRUG:	 MOXIFLOXACIN 
DRUG:	 TELITHROMYCIN 
DRUG:	 COUMARINS 
DRUG:	 ESCITALOPRAM  
HEADER	#### Antidepressants, Tricyclic %%%%
DRUG:	 MAOIS 
DRUG:	 FOSPHENYTOIN  
DRUG:	 PRIMIDONE  
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 FLUPHENAZINE 
DRUG:	 ZUCLOPENTHIXOL  
DRUG:	 RISPERIDONE 
DRUG:	 SAQUINAVIR 
DRUG:	 ATOMOXETINE 
DRUG:	 SOTALOL 
DRUG:	 CLONIDINE 
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 DAPOXETINE  
DRUG:	 ENTACAPONE 
HEADER	#### Antidepressants, Tricyclic %%%%
DRUG:	 SELEGILINE 
DRUG:	 METHYLTHIONINIUM 
DRUG:	 PENTAMIDINE ISETIONATE 
DRUG:	 PHENYLEPHRINE 
HEADER	#### Antidepressants, Tricyclic (related) %%%%
DRUG:	 ALCOHOL 
DRUG:	 MOCLOBEMIDE  
DRUG:	 CARBAMAZEPINE 
DRUG:	 PRIMIDONE  
DRUG:	 ARTEMETHER WITH LUMEFANTRINE  
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 RITONAVIR  
DRUG:	 TELAPREVIR 
HEADER	#### Antidiabetics %%%%
DRUG:	 NSAIDS 
DRUG:	 PARACETAMOL  
DRUG:	 RIFAMYCINS  
DRUG:	 TRIMETHOPRIM 
DRUG:	 COUMARINS 
DRUG:	 KETOCONAZOLE 
HEADER	#### Antidiabetics %%%%
DRUG:	 VORICONAZOLE 
DRUG:	 BOSENTAN 
DRUG:	 VANDETANIB  
DRUG:	 LOMITAPIDE 
DRUG:	 SULFINPYRAZONE 
HEADER	
HEADER	
HEADER	#### Antifungals, Imidazole %%%%
DRUG:	 TAMSULOSIN 
DRUG:	 AMINOPHYLLINE 
DRUG:	 PARACETAMOL 
DRUG:	 DRONEDARONE 
DRUG:	 TELITHROMYCIN 
DRUG:	 RIVAROXABAN 
DRUG:	 MIRTAZAPINE 
DRUG:	 GLIPIZIDE 
HEADER	#### Antifungals, Imidazole %%%%
DRUG:	 TOLBUTAMIDE 
DRUG:	 SULFONYLUREAS 
DRUG:	 CARBAMAZEPINE 
DRUG:	 PERAMPANEL 
DRUG:	 MIZOLASTINE  
DRUG:	 MEFLOQUINE 
DRUG:	 SOLIFENACIN 
DRUG:	 TOLTERODINE 
DRUG:	 QUETIAPINE 
DRUG:	 DACLATASVIR 
DRUG:	 DARUNAVIR 
DRUG:	 TELAPREVIR  
DRUG:	 ZOLPIDEM 
DRUG:	 AVANAFIL 
DRUG:	 DIHYDROPYRIDINES  
DRUG:	 CICLOSPORIN  
DRUG:	 CILOSTAZOL  
DRUG:	 CLOPIDOGREL 
DRUG:	 COLCHICINE  
DRUG:	 MOMETASONE 
DRUG:	 AXITINIB  
DRUG:	 PONATINIB 
DRUG:	 CRIZOTINIB 
DRUG:	 REGORAFENIB 
DRUG:	 VINFLUNINE 
DRUG:	 DAPOXETINE 
DRUG:	 EPLERENONE 
DRUG:	 DOMPERIDONE  
DRUG:	 ERGOTAMINE 
DRUG:	 FINGOLIMOD 
DRUG:	 ELETRIPTAN  
DRUG:	 IVABRADINE 
DRUG:	 IVACAFTOR  
DRUG:	 LENALIDOMIDE  
DRUG:	 ATORVASTATIN 
DRUG:	 LOMITAPIDE 
DRUG:	 NINTEDANIB 
DRUG:	 RANOLAZINE 
DRUG:	 ALITRETINOIN 
DRUG:	 TRETINOIN  
DRUG:	 SILDENAFIL 
DRUG:	 SIROLIMUS 
DRUG:	 SALMETEROL  
DRUG:	 TACROLIMUS 
DRUG:	 TADALAFIL 
DRUG:	 THEOPHYLLINE 
DRUG:	 TICAGRELOR 
DRUG:	 VARDENAFIL 
HEADER	
HEADER	#### Antifungals, Triazole %%%%
DRUG:	 ALISKIREN 
DRUG:	 AMINOPHYLLINE 
DRUG:	 IBUPROFEN  
DRUG:	 METHADONE  
DRUG:	 OXYCODONE 
DRUG:	 DRONEDARONE 
DRUG:	 RIFABUTIN  
DRUG:	 BEDAQUILINE 
DRUG:	 APIXABAN 
HEADER	#### Antifungals, Triazole %%%%
DRUG:	 RIVAROXABAN 
DRUG:	 GLIPIZIDE 
DRUG:	 SULFONYLUREAS 
DRUG:	 CARBAMAZEPINE 
DRUG:	 PHENYTOIN 
DRUG:	 PHENOBARBITAL 
DRUG:	 PRIMIDONE 
DRUG:	 MIZOLASTINE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 SOLIFENACIN 
DRUG:	 LURASIDONE  
DRUG:	 PIMOZIDE 
DRUG:	 RISPERIDONE 
DRUG:	 ATAZANAVIR  
HEADER	#### Antifungals, Triazole %%%%
DRUG:	 TIPRANAVIR 
DRUG:	 RITONAVIR 
DRUG:	 SAQUINAVIR 
DRUG:	 ZIDOVUDINE  
DRUG:	 DIAZEPAM  
DRUG:	 BUSPIRONE  
DRUG:	 AVANAFIL 
DRUG:	 BOSENTAN 
DRUG:	 CALCIUM-CHANNEL 
DRUG:	 DIHYDROPYRIDINES  
DRUG:	 DIGOXIN 
DRUG:	 CICLOSPORIN  
DRUG:	 CILOSTAZOL  
DRUG:	 CLOPIDOGREL 
DRUG:	 COLCHICINE  
DRUG:	 METHYLPREDNISOLONE 
HEADER	#### Antifungals, Triazole %%%%
DRUG:	 FLUTICASONE 
DRUG:	 BUSULFAN 
DRUG:	 CABOZANTINIB 
DRUG:	 PONATINIB 
DRUG:	 RUXOLITINIB 
DRUG:	 VINBLASTINE 
DRUG:	 VINCRISTINE  
DRUG:	 DAPOXETINE  
DRUG:	 HYDROCHLOROTHIAZIDE 
DRUG:	 DOMPERIDONE 
DRUG:	 ERGOTAMINE 
DRUG:	 ELETRIPTAN  
DRUG:	 IVABRADINE 
DRUG:	 IVACAFTOR  
DRUG:	 LENALIDOMIDE  
DRUG:	 ROSUVASTATIN 
DRUG:	 SIMVASTATIN 
DRUG:	 LOMITAPIDE  
DRUG:	 RANOLAZINE 
DRUG:	 TRETINOIN  
DRUG:	 SIROLIMUS 
DRUG:	 TACROLIMUS  
DRUG:	 THEOPHYLLINE 
DRUG:	 ESOMEPRAZOLE 
DRUG:	 RANITIDINE 
DRUG:	 PROTON PUMP INHIBITORS 
DRUG:	 VARDENAFIL 
HEADER	#### Antihistamines %%%%
DRUG:	 OPIOID ANALGESICS 
DRUG:	 PROPAFENONE  
DRUG:	 MACROLIDES  
DRUG:	 TRICYCLIC-RELATED ANTIDEPRESSANTS 
DRUG:	 IMIDAZOLES  
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 SAQUINAVIR 
DRUG:	 SOTALOL 
DRUG:	 VANDETANIB 
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	#### Antimuscarinics %%%%
DRUG:	 DISOPYRAMIDE 
DRUG:	 ITRACONAZOLE 
DRUG:	 ITRACONAZOLE 
DRUG:	 TIPRANAVIR 
DRUG:	 RITONAVIR  
DRUG:	 RITONAVIR 
DRUG:	 SOTALOL 
HEADER	#### Antipsychotics %%%%
DRUG:	 GENERAL ANAESTHETICS 
DRUG:	 OPIOID ANALGESICS 
DRUG:	 AMIODARONE 
DRUG:	 DISOPYRAMIDE 
DRUG:	 DISOPYRAMIDE 
DRUG:	 FLECAINIDE 
DRUG:	 TELITHROMYCIN 
DRUG:	 CLARITHROMYCIN 
HEADER	#### Antipsychotics %%%%
DRUG:	 ERYTHROMYCIN  
DRUG:	 ERYTHROMYCIN 
DRUG:	 CIPROFLOXACIN 
DRUG:	 MOXIFLOXACIN 
DRUG:	 CHLORAMPHENICOL  
DRUG:	 MACROLIDES  
DRUG:	 TELITHROMYCIN 
DRUG:	 FLUOXETINE  
DRUG:	 PAROXETINE  
DRUG:	 FLUVOXAMINE 
DRUG:	 SERTRALINE 
HEADER	#### Antipsychotics %%%%
DRUG:	 TRICYCLICS 
DRUG:	 CARBAMAZEPINE  
DRUG:	 CARBAMAZEPINE 
DRUG:	 PHENOBARBITAL 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE  
DRUG:	 VALPROIC ACID 
DRUG:	 FLUCONAZOLE  
DRUG:	 VORICONAZOLE 
DRUG:	 TRIAZOLES 
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 QUININE 
DRUG:	 MEFLOQUINE  
HEADER	#### Antipsychotics %%%%
DRUG:	 MEFLOQUINE 
DRUG:	 QUININE 
DRUG:	 HALOPERIDOL 
DRUG:	 ZUCLOPENTHIXOL  
DRUG:	 PIMOZIDE  
DRUG:	 SULPIRIDE 
DRUG:	 FOSAMPRENAVIR 
DRUG:	 SAQUINAVIR  
DRUG:	 LOPINAVIR 
DRUG:	 TIPRANAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 SAQUINAVIR  
DRUG:	 EFAVIRENZ  
DRUG:	 RITONAVIR  
DRUG:	 RITONAVIR 
DRUG:	 SAQUINAVIR 
DRUG:	 MIDAZOLAM 
HEADER	#### Antipsychotics %%%%
DRUG:	 BENZODIAZEPINES  
DRUG:	 BUSPIRONE 
DRUG:	 APREPITANT 
DRUG:	 ATOMOXETINE 
DRUG:	 SOTALOL 
DRUG:	 SOTALOL 
DRUG:	 VERAPAMIL  
DRUG:	 COBICISTAT 
DRUG:	 COBICISTAT 
DRUG:	 VANDETANIB 
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 DIURETICS 
DRUG:	 FOSAPREPITANT 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 TAMOXIFEN  
DRUG:	 IVABRADINE 
DRUG:	 LITHIUM 
DRUG:	 PENICILLAMINE  
DRUG:	 PENTAMIDINE ISETIONATE 
DRUG:	 TACROLIMUS  
HEADER	
HEADER	#### Anxiolytics and Hypnotics %%%%
DRUG:	 TELITHROMYCIN 
DRUG:	 ISONIAZID 
DRUG:	 TRICYCLICS 
DRUG:	 ITRACONAZOLE 
DRUG:	 VORICONAZOLE  
HEADER	#### Anxiolytics and Hypnotics %%%%
DRUG:	 ITRACONAZOLE  
DRUG:	 VORICONAZOLE  
DRUG:	 OLANZAPINE 
DRUG:	 ATAZANAVIR 
DRUG:	 INDINAVIR 
DRUG:	 TELAPREVIR  
DRUG:	 SIMEPREVIR 
DRUG:	 COBICISTAT 
DRUG:	 IDELALISIB 
DRUG:	 METHYLTHIONINIUM 
DRUG:	 SODIUM OXYBATE  
HEADER	#### Apixaban %%%%
DRUG:	 DICLOFENAC  
DRUG:	 KETOROLAC  
DRUG:	 TELITHROMYCIN 
DRUG:	 RIFAMPICIN 
DRUG:	 ANTICOAGULANTS  
DRUG:	 RIVAROXABAN  
DRUG:	 CARBAMAZEPINE 
DRUG:	 PHENYTOIN  
DRUG:	 PRIMIDONE 
DRUG:	 VORICONAZOLE 
HEADER	#### Apomorphine %%%%
DRUG:	 ONDANSETRON 
HEADER	#### Apraclonidine %%%%
HEADER	#### Aprepitant %%%%
DRUG:	 PIMOZIDE 
DRUG:	 AVANAFIL 
DRUG:	 IBRUTINIB 
DRUG:	 OESTROGENS  
DRUG:	 PROGESTOGENS  
HEADER	#### Argatroban %%%%
DRUG:	 DICLOFENAC  
DRUG:	 KETOROLAC  
DRUG:	 RIVAROXABAN  
HEADER	
HEADER	#### Arsenic Trioxide %%%%
DRUG:	 AMIODARONE  
DRUG:	 DISOPYRAMIDE 
DRUG:	 ERYTHROMYCIN 
DRUG:	 MOXIFLOXACIN 
DRUG:	 AMITRIPTYLINE  
DRUG:	 CLOMIPRAMINE 
DRUG:	 AMPHOTERICIN 
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 CLOZAPINE  
DRUG:	 SOTALOL 
DRUG:	 VANDETANIB 
DRUG:	 ACETAZOLAMIDE 
DRUG:	 THIAZIDES AND RELATED DIURETICS 
DRUG:	 LITHIUM 
HEADER	#### Artemether with Lumefantrine %%%%
DRUG:	 FLECAINIDE  
DRUG:	 MACROLIDES  
DRUG:	 QUINOLONES 
DRUG:	 ANTIDEPRESSANTS 
DRUG:	 IMIDAZOLES  
DRUG:	 TRIAZOLES 
DRUG:	 QUININE 
DRUG:	 ANTIPSYCHOTICS 
DRUG:	 INDINAVIR 
HEADER	#### Artemether with Lumefantrine %%%%
DRUG:	 TIPRANAVIR 
DRUG:	 ETRAVIRINE 
DRUG:	 METOPROLOL  
DRUG:	 SOTALOL 
DRUG:	 VANDETANIB 
DRUG:	 CIMETIDINE 
HEADER	#### Artenimol with Piperaquine %%%%
DRUG:	 METHADONE  
DRUG:	 AMIODARONE  
DRUG:	 DISOPYRAMIDE  
DRUG:	 MACROLIDES  
DRUG:	 RIFAMPICIN 
DRUG:	 ANTIDEPRESSANTS 
DRUG:	 IMIDAZOLES  
DRUG:	 TRIAZOLES  
DRUG:	 MIZOLASTINE  
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
DRUG:	 DROPERIDOL 
DRUG:	 PIMOZIDE  
DRUG:	 SAQUINAVIR  
DRUG:	 SOTALOL  
DRUG:	 VINFLUNINE  
DRUG:	 VINORELBINE 
DRUG:	 DOMPERIDONE  
DRUG:	 PENTAMIDINE ISETIONATE  
HEADER	#### Aspirin %%%%
DRUG:	 IBUPROFEN 
DRUG:	 HEPARINS 
DRUG:	 VENLAFAXINE 
DRUG:	 PEMETREXED 
DRUG:	 LOOP DIURETICS  
HEADER	#### Atazanavir %%%%
DRUG:	 LIDOCAINE 
DRUG:	 TELITHROMYCIN 
DRUG:	 VORICONAZOLE  
DRUG:	 QUININE  
DRUG:	 ARIPIPRAZOLE  
DRUG:	 QUETIAPINE 
DRUG:	 MARAVIROC  
DRUG:	 NEVIRAPINE 
DRUG:	 TIPRANAVIR  
DRUG:	 MIDAZOLAM 
DRUG:	 AVANAFIL 
DRUG:	 VERAPAMIL 
DRUG:	 CICLOSPORIN 
DRUG:	 COLCHICINE  
DRUG:	 IRINOTECAN  
DRUG:	 DAPOXETINE  
DRUG:	 ERGOT ALKALOIDS 
DRUG:	 PRAVASTATIN 
DRUG:	 SIMVASTATIN  
DRUG:	 ORLISTAT 
DRUG:	 RANOLAZINE 
DRUG:	 SILDENAFIL 
DRUG:	 SIROLIMUS 
DRUG:	 TACROLIMUS 
DRUG:	 TICAGRELOR 
DRUG:	 PROTON PUMP INHIBITORS 
HEADER	
HEADER	#### Atomoxetine %%%%
DRUG:	 TRAMADOL 
DRUG:	 AMIODARONE  
DRUG:	 DISOPYRAMIDE 
DRUG:	 MOXIFLOXACIN 
DRUG:	 TRICYCLICS 
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 SOTALOL 
DRUG:	 DIURETICS 
HEADER	
HEADER	#### Atovaquone %%%%
DRUG:	 TETRACYCLINE 
DRUG:	 ZIDOVUDINE  
HEADER	#### Avanafil %%%%
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 TELITHROMYCIN 
DRUG:	 RIFAMPICIN 
DRUG:	 KETOCONAZOLE 
DRUG:	 FLUCONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 EFAVIRENZ 
DRUG:	 FOSAMPRENAVIR 
DRUG:	 RITONAVIR 
DRUG:	 APREPITANT 
DRUG:	 VERAPAMIL 
DRUG:	 NICORANDIL  
DRUG:	 NITRATES  
DRUG:	 RIOCIGUAT 
HEADER	#### Axitinib %%%%
HEADER	#### Axitinib %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Azathioprine %%%%
DRUG:	 ALLOPURINOL  
DRUG:	 TRIMETHOPRIM  
DRUG:	 COUMARINS 
DRUG:	 RIBAVIRIN 
DRUG:	 FEBUXOSTAT 
HEADER	
HEADER	
HEADER	
HEADER	#### Aztreonam %%%%
DRUG:	 COUMARINS 
HEADER	#### Basiliximab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Bedaquiline %%%%
DRUG:	 CLOFAZIMINE 
DRUG:	 FOSPHENYTOIN  
DRUG:	 PHENYTOIN 
HEADER	#### Bee Venom Extracts %%%%
DRUG:	 ACE INHIBITORS 
HEADER	#### Belimumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Bendamustine %%%%
DRUG:	 CLOZAPINE  
HEADER	
HEADER	
HEADER	
HEADER	#### Beta-blockers %%%%
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 BUPIVACAINE 
DRUG:	 ANTI-ARRHYTHMICS 
DRUG:	 DRONEDARONE 
DRUG:	 PROPAFENONE 
DRUG:	 DELAMANID 
DRUG:	 ESCITALOPRAM 
HEADER	#### Beta-blockers %%%%
DRUG:	 TRICYCLICS 
DRUG:	 MIZOLASTINE 
DRUG:	 MEFLOQUINE 
DRUG:	 TOLTERODINE 
DRUG:	 PIMOZIDE  
DRUG:	 PHENOTHIAZINES 
DRUG:	 RISPERIDONE 
DRUG:	 TIPRANAVIR 
DRUG:	 ATOMOXETINE 
DRUG:	 VERAPAMIL  
DRUG:	 CICLOSPORIN 
DRUG:	 CLONIDINE  
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 THIAZIDES AND RELATED DIURETICS 
DRUG:	 FINGOLIMOD 
DRUG:	 IVABRADINE 
DRUG:	 MOXISYLYTE 
DRUG:	 RANOLAZINE 
DRUG:	 NORADRENALINE (NOREPINEPHRINE) 
HEADER	#### Betahistine %%%%
HEADER	#### Bevacizumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Bexarotene %%%%
DRUG:	 CLOZAPINE  
DRUG:	 GEMFIBROZIL 
HEADER	
HEADER	#### Bicalutamide %%%%
HEADER	
HEADER	
HEADER	
HEADER	#### Bile Acids %%%%
DRUG:	 CICLOSPORIN 
HEADER	
HEADER	#### Bisphosphonates %%%%
DRUG:	 ESTRAMUSTINE 
HEADER	#### Bivalirudin %%%%
DRUG:	 DICLOFENAC  
DRUG:	 KETOROLAC  
DRUG:	 RIVAROXABAN  
HEADER	#### Bleomycin %%%%
DRUG:	 CLOZAPINE  
DRUG:	 CISPLATIN 
HEADER	#### Boceprevir %%%%
DRUG:	 RIFAMPICIN  
DRUG:	 PRIMIDONE  
DRUG:	 KETOCONAZOLE 
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
DRUG:	 QUETIAPINE 
DRUG:	 RITONAVIR 
DRUG:	 MIDAZOLAM 
DRUG:	 CICLOSPORIN 
DRUG:	 CILOSTAZOL  
DRUG:	 IMATINIB 
DRUG:	 SORAFENIB  
DRUG:	 RUXOLITINIB 
DRUG:	 DOMPERIDONE 
DRUG:	 ERGOT ALKALOIDS 
DRUG:	 SIMVASTATIN 
DRUG:	 SIROLIMUS  
DRUG:	 TACROLIMUS  
HEADER	#### Bortezomib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 CLOZAPINE  
HEADER	#### Bosentan %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 GLIBENCLAMIDE 
DRUG:	 ITRACONAZOLE 
DRUG:	 TELAPREVIR 
DRUG:	 CICLOSPORIN  
DRUG:	 BOSUTINIB 
DRUG:	 OESTROGENS  
DRUG:	 PROGESTOGENS  
HEADER	#### Bosutinib %%%%
DRUG:	 METHADONE 
DRUG:	 AMIODARONE  
DRUG:	 DRONEDARONE 
DRUG:	 CLARITHROMYCIN 
DRUG:	 RIFAMPICIN 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 FLUCONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 HYDROXYCHLOROQUINE 
DRUG:	 CLOZAPINE  
DRUG:	 DARUNAVIR 
DRUG:	 SAQUINAVIR  
DRUG:	 ETRAVIRINE 
DRUG:	 APREPITANT 
DRUG:	 SOTALOL 
DRUG:	 BOSENTAN 
DRUG:	 VERAPAMIL 
DRUG:	 IMATINIB 
DRUG:	 DOMPERIDONE  
DRUG:	 FOSAPREPITANT 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 MODAFINIL 
HEADER	#### Brentuximab vedotin %%%%
DRUG:	 KETOCONAZOLE 
DRUG:	 CLOZAPINE  
DRUG:	 BLEOMYCIN 
DRUG:	 VACCINES 
HEADER	#### Brimonidine %%%%
HEADER	
HEADER	#### Bromocriptine %%%%
DRUG:	 ISOMETHEPTENE 
HEADER	#### Bupivacaine %%%%
DRUG:	 PROPRANOLOL 
HEADER	
HEADER	#### Bupropion %%%%
DRUG:	 TRICYCLICS  
DRUG:	 TAMOXIFEN  
DRUG:	 METHYLTHIONINIUM 
HEADER	
HEADER	#### Busulfan %%%%
DRUG:	 METRONIDAZOLE  
DRUG:	 CLOZAPINE  
HEADER	
HEADER	#### Cabazitaxel %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 PRIMIDONE 
DRUG:	 ITRACONAZOLE  
DRUG:	 VORICONAZOLE 
DRUG:	 CLOZAPINE  
DRUG:	 SAQUINAVIR 
HEADER	#### Cabergoline %%%%
HEADER	#### Cabozantinib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 CLOZAPINE  
HEADER	#### Caffeine citrate %%%%
HEADER	
HEADER	#### Calcium Salts %%%%
HEADER	#### Calcium-channel Blockers %%%%
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 AMINOPHYLLINE 
DRUG:	 AMINOPHYLLINE  
DRUG:	 GENERAL ANAESTHETICS  
DRUG:	 FLECAINIDE 
DRUG:	 DRONEDARONE 
DRUG:	 DRONEDARONE 
DRUG:	 RIFAMPICIN  
DRUG:	 FIDAXOMICIN 
DRUG:	 DABIGATRAN  
DRUG:	 IMIPRAMINE 
HEADER	#### Calcium-channel Blockers %%%%
DRUG:	 TRICYCLICS 
DRUG:	 PHENYTOIN  
DRUG:	 PHENYTOIN  
DRUG:	 PRIMIDONE 
DRUG:	 PRIMIDONE 
DRUG:	 PHENYTOIN 
DRUG:	 MICAFUNGIN 
DRUG:	 LURASIDONE  
DRUG:	 TELAPREVIR  
DRUG:	 AVANAFIL 
DRUG:	 BETA-BLOCKERS 
HEADER	#### Calcium-channel Blockers %%%%
DRUG:	 BETA-BLOCKERS 
DRUG:	 DIGOXIN 
DRUG:	 CICLOSPORIN  
DRUG:	 COLCHICINE  
DRUG:	 VINCRISTINE 
DRUG:	 FINGOLIMOD 
DRUG:	 IVABRADINE 
DRUG:	 LENALIDOMIDE  
DRUG:	 LOMITAPIDE  
DRUG:	 PARENTERAL MAGNESIUM  
DRUG:	 SIROLIMUS 
DRUG:	 TACROLIMUS 
DRUG:	 THEOPHYLLINE  
HEADER	
HEADER	
HEADER	#### Canakinumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	
HEADER	#### Cannabis Extract %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 TRICYCLICS 
DRUG:	 PRIMIDONE 
HEADER	#### Capecitabine %%%%
DRUG:	 ALLOPURINOL 
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
DRUG:	 FOLIC ACID 
HEADER	#### Capreomycin %%%%
HEADER	
HEADER	#### Carbamazepine %%%%
DRUG:	 PARACETAMOL  
DRUG:	 PRAZIQUANTEL 
DRUG:	 DRONEDARONE 
DRUG:	 ISONIAZID  
DRUG:	 TELITHROMYCIN  
DRUG:	 RIVAROXABAN 
DRUG:	 TRICYCLICS  
DRUG:	 OXCARBAZEPINE  
DRUG:	 PERAMPANEL  
DRUG:	 TOPIRAMATE 
DRUG:	 FLUCONAZOLE  
HEADER	#### Carbamazepine %%%%
DRUG:	 CASPOFUNGIN 
DRUG:	 MEFLOQUINE 
DRUG:	 RISPERIDONE 
DRUG:	 PALIPERIDONE 
DRUG:	 RILPIVIRINE  
DRUG:	 SAQUINAVIR  
DRUG:	 ETRAVIRINE 
DRUG:	 EFAVIRENZ 
DRUG:	 RITONAVIR 
DRUG:	 NIFEDIPINE 
DRUG:	 VERAPAMIL 
DRUG:	 CANNABIS EXTRACT 
DRUG:	 CICLOSPORIN  
DRUG:	 CLOPIDOGREL 
DRUG:	 COBICISTAT 
DRUG:	 CORTICOSTEROIDS  
DRUG:	 PONATINIB 
HEADER	#### Carbamazepine %%%%
DRUG:	 PROCARBAZINE 
DRUG:	 ACETAZOLAMIDE 
DRUG:	 EPLERENONE 
DRUG:	 TOREMIFENE  
DRUG:	 IVACAFTOR 
DRUG:	 SIMVASTATIN 
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
DRUG:	 CIMETIDINE  
DRUG:	 ULIPRISTAL  
HEADER	
HEADER	
HEADER	#### Cardiac Glycosides %%%%
DRUG:	 PROPAFENONE  
DRUG:	 ITRACONAZOLE 
DRUG:	 QUININE 
DRUG:	 TELAPREVIR 
DRUG:	 RITONAVIR 
DRUG:	 NICARDIPINE 
DRUG:	 NIFEDIPINE 
DRUG:	 VERAPAMIL 
DRUG:	 CICLOSPORIN  
DRUG:	 COLCHICINE 
DRUG:	 LOOP DIURETICS 
DRUG:	 POTASSIUM CANRENOATE 
DRUG:	 SPIRONOLACTONE 
DRUG:	 TICAGRELOR 
HEADER	#### Carmustine %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Caspofungin %%%%
DRUG:	 CICLOSPORIN  
DRUG:	 TACROLIMUS 
HEADER	#### Catumaxomab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	
HEADER	
HEADER	#### Cephalosporins %%%%
DRUG:	 COUMARINS 
HEADER	#### Certolizumab pegol %%%%
DRUG:	 ABATACEPT 
DRUG:	 ANAKINRA 
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	
HEADER	#### Cetuximab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Chloramphenicol %%%%
DRUG:	 COUMARINS 
DRUG:	 SULFONYLUREAS 
DRUG:	 PRIMIDONE  
DRUG:	 CLOZAPINE  
DRUG:	 CICLOSPORIN 
DRUG:	 CLOPIDOGREL 
DRUG:	 TACROLIMUS 
HEADER	
HEADER	#### Chloroprocaine %%%%
DRUG:	 SULFONAMIDES  
HEADER	#### Chloroquine %%%%
DRUG:	 PRAZIQUANTEL 
DRUG:	 AMIODARONE 
DRUG:	 MOXIFLOXACIN 
DRUG:	 ESCITALOPRAM 
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
DRUG:	 MEFLOQUINE 
DRUG:	 DROPERIDOL 
DRUG:	 DIGOXIN 
DRUG:	 CICLOSPORIN  
DRUG:	 BOSUTINIB 
HEADER	
HEADER	#### Ciclosporin %%%%
DRUG:	 ACE INHIBITORS 
DRUG:	 ALISKIREN 
DRUG:	 AMBRISENTAN  
DRUG:	 DICLOFENAC  
DRUG:	 ANGIOTENSIN-II RECEPTOR ANTAGONISTS 
DRUG:	 RIFAMPICIN  
DRUG:	 VANCOMYCIN 
HEADER	#### Ciclosporin %%%%
DRUG:	 TRIMETHOPRIM 
DRUG:	 DABIGATRAN 
DRUG:	 PHENOBARBITAL 
DRUG:	 OXCARBAZEPINE 
DRUG:	 KETOCONAZOLE 
DRUG:	 MICONAZOLE  
DRUG:	 MICAFUNGIN 
DRUG:	 HYDROXYCHLOROQUINE  
DRUG:	 ATAZANAVIR  
DRUG:	 RITONAVIR 
DRUG:	 INDINAVIR 
DRUG:	 SAQUINAVIR 
DRUG:	 TELAPREVIR  
DRUG:	 CARVEDILOL 
DRUG:	 URSODEOXYCHOLIC ACID 
DRUG:	 BOSENTAN  
DRUG:	 NICARDIPINE  
DRUG:	 NIFEDIPINE  
DRUG:	 DIGOXIN  
DRUG:	 COLCHICINE 
DRUG:	 PREDNISOLONE 
DRUG:	 AFATINIB 
DRUG:	 CRIZOTINIB 
DRUG:	 ETOPOSIDE  
DRUG:	 POTASSIUM- SPARING DIURETICS AND ALDOSTERONE ANTAGONISTS 
DRUG:	 THIAZIDES AND RELATED DIURETICS 
DRUG:	 GRAPEFRUIT JUICE  
DRUG:	 LANREOTIDE  
DRUG:	 PASIREOTIDE 
DRUG:	 LENALIDOMIDE  
DRUG:	 PRAVASTATIN 
DRUG:	 LOMITAPIDE 
DRUG:	 METOCLOPRAMIDE 
DRUG:	 MODAFINIL 
DRUG:	 ORLISTAT 
DRUG:	 POTASSIUM SALTS 
DRUG:	 SULFINPYRAZONE 
DRUG:	 TACROLIMUS  
DRUG:	 OMEPRAZOLE 
HEADER	#### Cilostazol %%%%
DRUG:	 ANAGRELIDE 
DRUG:	 CLARITHROMYCIN  
DRUG:	 ERYTHROMYCIN  
DRUG:	 KETOCONAZOLE  
DRUG:	 ITRACONAZOLE  
DRUG:	 TELAPREVIR  
DRUG:	 OMEPRAZOLE  
HEADER	
HEADER	#### Cinacalcet %%%%
DRUG:	 TAMOXIFEN  
HEADER	#### Cladribine %%%%
DRUG:	 CLOZAPINE  
DRUG:	 LAMIVUDINE 
HEADER	#### Clindamycin %%%%
DRUG:	 NON- 
DRUG:	 SUXAMETHONIUM 
HEADER	
HEADER	#### Clofazimine %%%%
DRUG:	 BEDAQUILINE 
HEADER	#### Clonidine %%%%
DRUG:	 TRICYCLICS 
DRUG:	 BETA-BLOCKERS  
DRUG:	 NORADRENALINE (NOREPINEPHRINE) 
DRUG:	 METHYLPHENIDATE  
HEADER	
HEADER	#### Clopidogrel %%%%
DRUG:	 CIPROFLOXACIN  
DRUG:	 ERYTHROMYCIN 
DRUG:	 HEPARINS 
DRUG:	 MOCLOBEMIDE 
DRUG:	 OXCARBAZEPINE 
DRUG:	 KETOCONAZOLE  
DRUG:	 VORICONAZOLE 
DRUG:	 ETRAVIRINE 
DRUG:	 ROSUVASTATIN 
DRUG:	 PANTOPRAZOLE  
DRUG:	 RABEPRAZOLE 
DRUG:	 OMEPRAZOLE 
HEADER	#### Co-beneldopa %%%%
DRUG:	 VOLATILE LIQUID GENERAL ANAESTHETICS 
DRUG:	 MOCLOBEMIDE 
HEADER	#### Cobicistat %%%%
DRUG:	 ALFUZOSIN 
DRUG:	 AMIODARONE 
DRUG:	 RIFABUTIN  
DRUG:	 RIFAMPICIN 
DRUG:	 RIVAROXABAN 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 LURASIDONE 
DRUG:	 PIMOZIDE 
DRUG:	 DACLATASVIR 
DRUG:	 TIPRANAVIR  
DRUG:	 MIDAZOLAM 
DRUG:	 IBRUTINIB 
DRUG:	 DOMPERIDONE 
DRUG:	 ERGOT ALKALOIDS 
DRUG:	 SIMVASTATIN 
DRUG:	 OESTROGENS 
DRUG:	 SILDENAFIL 
HEADER	#### Cobicistat %%%%
DRUG:	 TADALAFIL 
DRUG:	 VARDENAFIL 
HEADER	#### Co-careldopa %%%%
DRUG:	 VOLATILE LIQUID GENERAL ANAESTHETICS 
DRUG:	 MOCLOBEMIDE 
HEADER	#### Colchicine %%%%
DRUG:	 AMIODARONE 
DRUG:	 CLARITHROMYCIN 
DRUG:	 TELITHROMYCIN 
DRUG:	 KETOCONAZOLE 
DRUG:	 RITONAVIR  
DRUG:	 TELAPREVIR 
DRUG:	 VERAPAMIL 
DRUG:	 DIGOXIN 
DRUG:	 CICLOSPORIN 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 STATINS 
HEADER	
HEADER	#### Colesevelam %%%%
DRUG:	 CICLOSPORIN 
HEADER	#### Colestilan %%%%
HEADER	#### Colestipol %%%%
HEADER	#### Colestyramine %%%%
DRUG:	 PHENINDIONE 
HEADER	#### Corticosteroids %%%%
DRUG:	 ALDESLEUKIN 
DRUG:	 CLARITHROMYCIN 
HEADER	#### Corticosteroids %%%%
DRUG:	 RIFAMYCINS  
DRUG:	 PHENINDIONE 
DRUG:	 PHENOBARBITAL 
DRUG:	 PRIMIDONE  
DRUG:	 KETOCONAZOLE 
DRUG:	 KETOCONAZOLE 
DRUG:	 CASPOFUNGIN 
DRUG:	 TELAPREVIR 
DRUG:	 RITONAVIR 
DRUG:	 RITONAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 CICLOSPORIN 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 VACCINES 
HEADER	
HEADER	#### Coumarins %%%%
DRUG:	 ALCOHOL 
DRUG:	 ANABOLIC STEROIDS 
DRUG:	 DICLOFENAC  
DRUG:	 KETOROLAC  
DRUG:	 PARACETAMOL 
DRUG:	 LEVAMISOLE 
DRUG:	 PROPAFENONE 
DRUG:	 TIGECYCLINE  
DRUG:	 NORFLOXACIN 
DRUG:	 RIFAMYCINS  
DRUG:	 RIVAROXABAN  
DRUG:	 TRICYCLICS 
DRUG:	 SULFONYLUREAS 
DRUG:	 PRIMIDONE  
DRUG:	 VALPROIC ACID 
DRUG:	 KETOCONAZOLE  
DRUG:	 GRISEOFULVIN 
DRUG:	 RITONAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 AZATHIOPRINE 
DRUG:	 CLOPIDOGREL 
DRUG:	 CORTICOSTEROIDS  
DRUG:	 CRANBERRY JUICE 
DRUG:	 SORAFENIB 
DRUG:	 MERCAPTOPURINE  
DRUG:	 REGORAFENIB 
DRUG:	 DIPYRIDAMOLE 
DRUG:	 DISULFIRAM 
DRUG:	 ENTACAPONE 
DRUG:	 ENTERAL FEEDS  
DRUG:	 GLUCOSAMINE  
DRUG:	 TAMOXIFEN 
DRUG:	 EZETIMIBE  
DRUG:	 LOMITAPIDE 
DRUG:	 ACITRETIN 
DRUG:	 SULFINPYRAZONE 
DRUG:	 METHYLPHENIDATE 
DRUG:	 TESTOLACTONE 
DRUG:	 TESTOSTERONE 
DRUG:	 THYROID HORMONES 
DRUG:	 SUCRALFATE  
DRUG:	 VITAMIN K 
HEADER	#### Cranberry Juice %%%%
DRUG:	 COUMARINS 
HEADER	#### Crizotinib %%%%
DRUG:	 FENTANYL 
DRUG:	 RIFAMPICIN 
DRUG:	 KETOCONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 PIMOZIDE 
DRUG:	 SAQUINAVIR 
DRUG:	 MIDAZOLAM 
DRUG:	 CICLOSPORIN 
DRUG:	 IBRUTINIB 
DRUG:	 ERGOT ALKALOIDS 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 OESTROGENS  
DRUG:	 PROGESTOGENS  
DRUG:	 SIROLIMUS 
DRUG:	 TACROLIMUS 
HEADER	#### Cyclophosphamide %%%%
DRUG:	 CLOZAPINE  
DRUG:	 PENTOSTATIN 
HEADER	#### Cycloserine %%%%
DRUG:	 ALCOHOL 
HEADER	
HEADER	#### Cytarabine %%%%
DRUG:	 CLOZAPINE  
HEADER	
HEADER	#### Dabigatran %%%%
DRUG:	 KETOROLAC  
DRUG:	 AMIODARONE  
DRUG:	 DRONEDARONE 
DRUG:	 RIFAMPICIN 
DRUG:	 RIVAROXABAN  
DRUG:	 SSRI-RELATED ANTIDEPRESSANTS  
DRUG:	 SSRIS 
HEADER	#### Dabigatran %%%%
DRUG:	 ITRACONAZOLE 
DRUG:	 VERAPAMIL  
DRUG:	 CICLOSPORIN 
DRUG:	 SULFINPYRAZONE 
DRUG:	 TACROLIMUS 
DRUG:	 TICAGRELOR 
HEADER	#### Dabrafenib %%%%
DRUG:	 CLOZAPINE  
DRUG:	 OESTROGENS  
DRUG:	 PROGESTOGENS  
HEADER	#### Dacarbazine %%%%
DRUG:	 ALDESLEUKIN 
DRUG:	 CLOZAPINE  
HEADER	#### Daclatasvir %%%%
DRUG:	 AMIODARONE 
DRUG:	 TELITHROMYCIN 
DRUG:	 RIFAMPICIN 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PHENYTOIN  
HEADER	#### Daclatasvir %%%%
DRUG:	 PRIMIDONE 
DRUG:	 POSACONAZOLE  
DRUG:	 VORICONAZOLE 
DRUG:	 BOCEPREVIR 
DRUG:	 LOPINAVIR  
DRUG:	 NEVIRAPINE  
DRUG:	 DIGOXIN 
DRUG:	 COBICISTAT 
HEADER	#### Dactinomycin %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Dairy Products %%%%
HEADER	
HEADER	#### Danaparoid %%%%
DRUG:	 DICLOFENAC  
DRUG:	 KETOROLAC  
DRUG:	 RIVAROXABAN  
HEADER	#### Danazol %%%%
DRUG:	 COUMARINS 
DRUG:	 CARBAMAZEPINE  
DRUG:	 CICLOSPORIN 
DRUG:	 SIMVASTATIN 
HEADER	#### Dapoxetine %%%%
DRUG:	 ALCOHOL 
DRUG:	 TRAMADOL  
DRUG:	 ERYTHROMYCIN  
DRUG:	 TELITHROMYCIN  
DRUG:	 MAOIS  
DRUG:	 ITRACONAZOLE  
DRUG:	 RITONAVIR  
DRUG:	 FOSAMPRENAVIR  
DRUG:	 5HT1 AGONISTS  
DRUG:	 LITHIUM  
HEADER	#### Dapsone %%%%
DRUG:	 SAQUINAVIR 
HEADER	#### Daptomycin %%%%
DRUG:	 CICLOSPORIN  
DRUG:	 STATINS  
HEADER	
HEADER	#### Darunavir %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
DRUG:	 QUININE  
DRUG:	 ARIPIPRAZOLE  
DRUG:	 QUETIAPINE 
DRUG:	 DIDANOSINE  
DRUG:	 SIMEPREVIR 
DRUG:	 BOSUTINIB 
DRUG:	 IBRUTINIB 
DRUG:	 ERGOT ALKALOIDS 
DRUG:	 LOMITAPIDE  
DRUG:	 ORLISTAT 
DRUG:	 RANOLAZINE 
HEADER	#### Dasatinib %%%%
DRUG:	 ERYTHROMYCIN  
HEADER	#### Dasatinib %%%%
DRUG:	 TELITHROMYCIN  
DRUG:	 RIFAMPICIN  
DRUG:	 CLOZAPINE  
DRUG:	 RITONAVIR  
HEADER	#### Decitabine %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Deferasirox %%%%
DRUG:	 AMINOPHYLLINE  
DRUG:	 THEOPHYLLINE  
HEADER	#### Deferiprone %%%%
HEADER	
HEADER	#### Delamanid %%%%
DRUG:	 METHADONE 
DRUG:	 DISOPYRAMIDE 
DRUG:	 ETHAMBUTOL 
DRUG:	 TRICYCLICS  
DRUG:	 HALOPERIDOL  
DRUG:	 PHENOTHIAZINES  
DRUG:	 SAQUINAVIR 
DRUG:	 SOTALOL 
DRUG:	 VINCRISTINE 
DRUG:	 VINORELBINE 
DRUG:	 DOMPERIDONE 
DRUG:	 PENTAMIDINE ISETIONATE 
HEADER	
HEADER	#### Desferrioxamine %%%%
HEADER	#### Desmopressin %%%%
HEADER	#### Dexrazoxane %%%%
DRUG:	 PHENYTOIN 
DRUG:	 VACCINES 
HEADER	#### Diazoxide %%%%
HEADER	#### Didanosine %%%%
DRUG:	 ALLOPURINOL  
DRUG:	 TIPRANAVIR 
DRUG:	 HYDROXYCARBAMIDE 
DRUG:	 ORLISTAT 
HEADER	
HEADER	#### Diethylcarbamazine %%%%
HEADER	#### Dimethyl sulfoxide %%%%
DRUG:	 SULINDAC 
HEADER	
HEADER	#### Dipyridamole %%%%
DRUG:	 ADENOSINE  
DRUG:	 HEPARINS 
HEADER	#### Disopyramide %%%%
DRUG:	 DRONEDARONE 
DRUG:	 CLARITHROMYCIN  
DRUG:	 ERYTHROMYCIN  
DRUG:	 MOXIFLOXACIN 
DRUG:	 DELAMANID 
DRUG:	 TELITHROMYCIN 
DRUG:	 TRICYCLICS 
DRUG:	 KETOCONAZOLE 
DRUG:	 ITRACONAZOLE 
DRUG:	 MIZOLASTINE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 TOLTERODINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 PIMOZIDE  
DRUG:	 SULPIRIDE 
DRUG:	 TELAPREVIR  
DRUG:	 ATOMOXETINE 
DRUG:	 BETA-BLOCKERS 
DRUG:	 SOTALOL 
DRUG:	 VERAPAMIL 
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 LOOP DIURETICS 
DRUG:	 THIAZIDES AND RELATED DIURETICS 
DRUG:	 FINGOLIMOD 
DRUG:	 IVABRADINE 
DRUG:	 PENTAMIDINE ISETIONATE 
DRUG:	 RANOLAZINE 
HEADER	#### Disulfiram %%%%
DRUG:	 COUMARINS 
DRUG:	 PHENYTOIN  
DRUG:	 PARALDEHYDE 
HEADER	#### Diuretics %%%%
DRUG:	 ACE INHIBITORS 
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 ASPIRIN  
DRUG:	 ANGIOTENSIN-II RECEPTOR ANTAGONISTS 
DRUG:	 FLECAINIDE 
DRUG:	 LIDOCAINE 
DRUG:	 ERYTHROMYCIN  
DRUG:	 TRIMETHOPRIM 
DRUG:	 REBOXETINE 
HEADER	#### Diuretics %%%%
DRUG:	 TRICYCLICS 
DRUG:	 PHENOBARBITAL 
DRUG:	 PRIMIDONE 
DRUG:	 ZONISAMIDE 
DRUG:	 FLUCONAZOLE  
DRUG:	 PIMOZIDE  
DRUG:	 SAQUINAVIR  
DRUG:	 ATOMOXETINE 
DRUG:	 SOTALOL 
DRUG:	 DIGOXIN 
DRUG:	 CICLOSPORIN 
HEADER	#### Diuretics %%%%
DRUG:	 METHOTREXATE 
DRUG:	 PLATINUM COMPOUNDS 
DRUG:	 LITHIUM 
DRUG:	 POTASSIUM SALTS 
DRUG:	 TACROLIMUS 
HEADER	
HEADER	#### Diuretics, Potassium-sparing and Aldosterone Antagonists  %%%%see
HEADER	
HEADER	
HEADER	#### Docetaxel %%%%
DRUG:	 TELITHROMYCIN 
DRUG:	 VORICONAZOLE 
DRUG:	 CLOZAPINE  
DRUG:	 SAQUINAVIR 
HEADER	#### Dolutegravir %%%%
DRUG:	 RIFAMPICIN  
DRUG:	 NEVIRAPINE  
HEADER	#### Domperidone %%%%
DRUG:	 DELAMANID 
DRUG:	 VORICONAZOLE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 RITONAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 COBICISTAT 
DRUG:	 BOSUTINIB  
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	#### Doxapram %%%%
DRUG:	 VOLATILE LIQUID GENERAL ANAESTHETICS  
HEADER	
HEADER	
HEADER	#### Doxorubicin %%%%
DRUG:	 CLOZAPINE  
DRUG:	 CICLOSPORIN 
DRUG:	 VACCINES 
HEADER	
HEADER	#### Dronedarone %%%%
DRUG:	 DISOPYRAMIDE 
DRUG:	 TELITHROMYCIN 
DRUG:	 RIVAROXABAN 
DRUG:	 TRICYCLICS  
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 KETOCONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 PHENOTHIAZINES  
DRUG:	 SAQUINAVIR 
DRUG:	 SOTALOL 
DRUG:	 NIFEDIPINE 
DRUG:	 VERAPAMIL 
DRUG:	 DIGOXIN  
DRUG:	 IBRUTINIB 
DRUG:	 FINGOLIMOD 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 SIMVASTATIN 
DRUG:	 LOMITAPIDE  
HEADER	#### Duloxetine %%%%
DRUG:	 CIPROFLOXACIN 
DRUG:	 DABIGATRAN 
DRUG:	 MOCLOBEMIDE  
DRUG:	 MOCLOBEMIDE  
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 DAPOXETINE  
DRUG:	 METHYLTHIONINIUM 
HEADER	#### Dutasteride %%%%
HEADER	
HEADER	#### Efavirenz %%%%
DRUG:	 COUMARINS 
DRUG:	 POSACONAZOLE 
DRUG:	 CASPOFUNGIN 
DRUG:	 PROGUANIL 
DRUG:	 PIMOZIDE  
DRUG:	 ATAZANAVIR  
DRUG:	 DARUNAVIR  
DRUG:	 ELVITEGRAVIR 
DRUG:	 RITONAVIR 
HEADER	#### Efavirenz %%%%
DRUG:	 TELAPREVIR 
DRUG:	 MIDAZOLAM 
DRUG:	 ATOVAQUONE 
DRUG:	 CICLOSPORIN 
DRUG:	 BOSUTINIB 
DRUG:	 ERGOT ALKALOIDS 
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS 
DRUG:	 TACROLIMUS 
HEADER	
HEADER	#### Eltrombopag %%%%
DRUG:	 ROSUVASTATIN 
HEADER	#### Elvitegravir %%%%
DRUG:	 RIFABUTIN  
DRUG:	 RIFAMPICIN 
DRUG:	 PRIMIDONE 
DRUG:	 NEVIRAPINE 
DRUG:	 ORLISTAT 
HEADER	
HEADER	#### Emtricitabine %%%%
DRUG:	 ORLISTAT 
HEADER	
HEADER	#### Enfuvirtide %%%%
DRUG:	 ORLISTAT 
HEADER	
HEADER	
HEADER	#### Entacapone %%%%
DRUG:	 WARFARIN 
DRUG:	 VENLAFAXINE 
DRUG:	 MAOIS 
HEADER	#### Enteral Foods %%%%
DRUG:	 PHENINDIONE 
HEADER	#### Enzalutamide %%%%
DRUG:	 COUMARINS 
DRUG:	 GEMFIBROZIL 
HEADER	
HEADER	#### Epinephrine %%%%
HEADER	#### Epirubicin %%%%
DRUG:	 CLOZAPINE  
DRUG:	 CICLOSPORIN 
DRUG:	 CIMETIDINE 
HEADER	
HEADER	
HEADER	#### Eptifibatide %%%%
HEADER	#### Ergot Alkaloids %%%%
DRUG:	 TETRACYCLINES 
DRUG:	 IMIDAZOLES  
DRUG:	 TRIAZOLES 
DRUG:	 ATAZANAVIR 
DRUG:	 RITONAVIR  
DRUG:	 INDINAVIR  
DRUG:	 RITONAVIR 
DRUG:	 COBICISTAT 
DRUG:	 IDELALISIB 
DRUG:	 RIZATRIPTAN 
DRUG:	 ELETRIPTAN 
DRUG:	 NARATRIPTAN  
DRUG:	 TICAGRELOR 
DRUG:	 CIMETIDINE 
HEADER	
HEADER	#### Eribulin %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Erlotinib %%%%
DRUG:	 NSAIDS 
DRUG:	 ANTACIDS 
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
DRUG:	 BOCEPREVIR 
DRUG:	 ESOMEPRAZOLE 
DRUG:	 PANTOPRAZOLE 
DRUG:	 OMEPRAZOLE 
HEADER	#### Ertapenem %%%%
DRUG:	 VALPROIC ACID 
HEADER	#### Eslicarbazepine %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
HEADER	
HEADER	
HEADER	
HEADER	#### Estramustine %%%%
DRUG:	 CLOZAPINE  
DRUG:	 SODIUM CLODRONATE 
HEADER	#### Etanercept %%%%
DRUG:	 ABATACEPT 
DRUG:	 ANAKINRA 
DRUG:	 VACCINES 
HEADER	#### Ethambutol %%%%
HEADER	
HEADER	#### Ethosuximide %%%%
DRUG:	 ISONIAZID  
DRUG:	 TRICYCLICS  
DRUG:	 PRIMIDONE 
DRUG:	 VALPROIC ACID 
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	
HEADER	#### Etoposide %%%%
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
HEADER	
HEADER	#### Etravirine %%%%
DRUG:	 BEDAQUILINE 
DRUG:	 NEVIRAPINE 
HEADER	#### Etravirine %%%%
DRUG:	 TIPRANAVIR 
DRUG:	 CLOPIDOGREL 
DRUG:	 BOSUTINIB 
DRUG:	 ORLISTAT 
HEADER	#### Everolimus %%%%
DRUG:	 ACE INHIBITORS 
DRUG:	 TELITHROMYCIN 
DRUG:	 RIFAMPICIN  
DRUG:	 POSACONAZOLE  
DRUG:	 VORICONAZOLE 
DRUG:	 CLOZAPINE  
DRUG:	 INDINAVIR 
DRUG:	 SAQUINAVIR 
DRUG:	 VERAPAMIL  
DRUG:	 CICLOSPORIN  
DRUG:	 IMATINIB  
HEADER	#### Exemestane %%%%
HEADER	
HEADER	#### Ezetimibe %%%%
DRUG:	 CICLOSPORIN 
DRUG:	 ROSUVASTATIN 
HEADER	#### Ezetimibe %%%%
DRUG:	 Fampridine 
DRUG:	 CIMETIDINE 
HEADER	#### Febuxostat %%%%
DRUG:	 AZATHIOPRINE 
DRUG:	 MERCAPTOPURINE 
HEADER	
HEADER	
HEADER	#### Fibrates %%%%
DRUG:	 DAPTOMYCIN  
DRUG:	 PHENINDIONE 
DRUG:	 REPAGLINIDE 
DRUG:	 COLCHICINE 
DRUG:	 BEXAROTENE 
DRUG:	 ENZALUTAMIDE 
DRUG:	 FLUVASTATIN  
DRUG:	 STATINS 
HEADER	#### Fidaxomicin %%%%
HEADER	#### Filgrastim %%%%
HEADER	#### Fingolimod %%%%
DRUG:	 DISOPYRAMIDE  
DRUG:	 DRONEDARONE 
DRUG:	 KETOCONAZOLE 
DRUG:	 BETA-BLOCKERS 
DRUG:	 VERAPAMIL 
HEADER	
HEADER	#### Flecainide %%%%
DRUG:	 AMIODARONE  
DRUG:	 TRICYCLICS 
DRUG:	 MIZOLASTINE 
DRUG:	 QUININE 
DRUG:	 TOLTERODINE 
DRUG:	 CLOZAPINE 
DRUG:	 LOPINAVIR  
DRUG:	 SAQUINAVIR 
DRUG:	 TELAPREVIR  
DRUG:	 BETA-BLOCKERS 
DRUG:	 VERAPAMIL 
DRUG:	 LOOP DIURETICS 
DRUG:	 THIAZIDES AND RELATED DIURETICS 
HEADER	#### Flucytosine %%%%
HEADER	#### Fludarabine %%%%
DRUG:	 CLOZAPINE  
DRUG:	 CYTARABINE 
HEADER	#### Fludarabine %%%%
DRUG:	 PENTOSTATIN  
HEADER	
HEADER	#### Fluorides %%%%
HEADER	#### Fluorouracil %%%%
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
DRUG:	 FOLIC ACID 
DRUG:	 TEMOPORFIN 
HEADER	
HEADER	#### Flutamide %%%%
DRUG:	 COUMARINS 
HEADER	
HEADER	
HEADER	
HEADER	#### Folates %%%%
DRUG:	 TEGAFUR 
DRUG:	 RALTITREXED 
HEADER	#### Fondaparinux %%%%
DRUG:	 DICLOFENAC  
DRUG:	 KETOROLAC  
DRUG:	 RIVAROXABAN  
HEADER	
HEADER	#### Fosamprenavir %%%%
DRUG:	 FLECAINIDE  
DRUG:	 PROPAFENONE  
HEADER	#### Fosamprenavir %%%%
DRUG:	 LIDOCAINE 
DRUG:	 TELITHROMYCIN 
DRUG:	 QUININE  
DRUG:	 QUETIAPINE 
DRUG:	 RALTEGRAVIR 
DRUG:	 LOPINAVIR 
DRUG:	 TIPRANAVIR 
DRUG:	 MIDAZOLAM  
DRUG:	 AVANAFIL 
DRUG:	 CICLOSPORIN 
DRUG:	 IBRUTINIB 
DRUG:	 ERGOTAMINE 
DRUG:	 SIMVASTATIN 
HEADER	#### Fosamprenavir %%%%
DRUG:	 LOMITAPIDE  
DRUG:	 ORLISTAT 
DRUG:	 RANOLAZINE 
DRUG:	 TACROLIMUS 
HEADER	#### Fosaprepitant %%%%
DRUG:	 PIMOZIDE 
DRUG:	 IBRUTINIB 
DRUG:	 OESTROGENS 
DRUG:	 PROGESTOGENS  
HEADER	#### Foscarnet %%%%
DRUG:	 PENTAMIDINE ISETIONATE 
HEADER	#### Fosfomycin %%%%
HEADER	
HEADER	#### Fosphenytoin %%%%
DRUG:	 AMINOPHYLLINE 
DRUG:	 ACEMETACIN  
HEADER	#### Fosphenytoin %%%%
DRUG:	 PARACETAMOL  
DRUG:	 LEVAMISOLE 
DRUG:	 DISOPYRAMIDE 
DRUG:	 DRONEDARONE 
DRUG:	 BEDAQUILINE 
DRUG:	 ISONIAZID   
DRUG:	 TRIMETHOPRIM  
DRUG:	 RIVAROXABAN 
DRUG:	 TRICYCLICS 
DRUG:	 OXCARBAZEPINE 
HEADER	#### Fosphenytoin %%%%
DRUG:	 VIGABATRIN 
DRUG:	 CASPOFUNGIN 
DRUG:	 MEFLOQUINE 
DRUG:	 PYRIMETHAMINE 
DRUG:	 LURASIDONE 
DRUG:	 RILPIVIRINE  
DRUG:	 DOLUTEGRAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 ZIDOVUDINE 
DRUG:	 DILTIAZEM  
DRUG:	 CANNABIS EXTRACT 
DRUG:	 CICLOSPORIN  
DRUG:	 COBICISTAT 
DRUG:	 CORTICOSTEROIDS  
DRUG:	 BORTEZOMIB 
DRUG:	 IDELALISIB  
DRUG:	 CABOZANTINIB 
DRUG:	 LAPATINIB  
DRUG:	 PROCARBAZINE 
DRUG:	 DEXRAZOXANE 
DRUG:	 DISULFIRAM  
DRUG:	 CARBONIC ANHYDRASE INHIBITORS 
DRUG:	 TOREMIFENE 
DRUG:	 IVACAFTOR 
DRUG:	 NON-DEPOLARISING MUSCLE RELAXANTS  
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
DRUG:	 SULFINPYRAZONE 
DRUG:	 THEOPHYLLINE 
DRUG:	 SUCRALFATE 
DRUG:	 ULIPRISTAL  
HEADER	
HEADER	
HEADER	#### Fusidic Acid %%%%
DRUG:	 SAQUINAVIR 
DRUG:	 STATINS 
HEADER	#### Gabapentin %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	
HEADER	#### Ganciclovir %%%%
DRUG:	 IMIPENEM WITH CILASTATIN 
DRUG:	 ZIDOVUDINE  
HEADER	#### Gefitinib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 WARFARIN 
DRUG:	 CLOZAPINE  
DRUG:	 BOCEPREVIR 
DRUG:	 RANITIDINE 
HEADER	#### Gemcitabine %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Glucosamine %%%%
DRUG:	 Golimumab 
DRUG:	 ABATACEPT 
DRUG:	 ANAKINRA 
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	
HEADER	#### Grapefruit Juice %%%%
DRUG:	 ALISKIREN 
DRUG:	 DRONEDARONE 
DRUG:	 QUETIAPINE 
DRUG:	 CICLOSPORIN  
DRUG:	 COLCHICINE  
DRUG:	 BUDESONIDE 
DRUG:	 IBRUTINIB 
DRUG:	 PAZOPANIB 
DRUG:	 LOMITAPIDE 
DRUG:	 RANOLAZINE 
DRUG:	 SIROLIMUS 
DRUG:	 TACROLIMUS 
DRUG:	 TOLVAPTAN 
DRUG:	 VARDENAFIL 
HEADER	#### Griseofulvin %%%%
DRUG:	 COUMARINS 
HEADER	
HEADER	
HEADER	#### Heparins %%%%
DRUG:	 DICLOFENAC  
DRUG:	 ASPIRIN 
DRUG:	 RIVAROXABAN  
DRUG:	 GLYCERYL TRINITRATE 
HEADER	
HEADER	#### Histamine %%%%
HEADER	#### Histamine H2-antagonists %%%%
DRUG:	 TOLAZOLINE 
DRUG:	 AMINOPHYLLINE  
DRUG:	 LIDOCAINE  
DRUG:	 COUMARINS 
DRUG:	 SODIUM 
DRUG:	 VALPROIC ACID  
DRUG:	 TERBINAFINE 
DRUG:	 QUININE  
DRUG:	 ATAZANAVIR  
HEADER	#### Histamine H2-antagonists %%%%
DRUG:	 SAQUINAVIR 
DRUG:	 CICLOSPORIN 
DRUG:	 CLOPIDOGREL 
DRUG:	 ERLOTINIB 
DRUG:	 PAZOPANIB 
DRUG:	 ERGOTAMINE 
DRUG:	 FAMPRIDINE 
DRUG:	 THEOPHYLLINE  
HEADER	
HEADER	
HEADER	#### 5HT1-receptor Agonists %%%%
DRUG:	 ERYTHROMYCIN  
HEADER	#### 5HT1-receptor Agonists %%%%
DRUG:	 QUINOLONES  
DRUG:	 CITALOPRAM 
DRUG:	 FLUVOXAMINE  
DRUG:	 MAOIS  
DRUG:	 MOCLOBEMIDE  
DRUG:	 KETOCONAZOLE  
DRUG:	 RITONAVIR  
DRUG:	 DAPOXETINE  
DRUG:	 ERGOTAMINE  
HEADER	#### 5HT3-receptor Antagonists %%%%
DRUG:	 VANDETANIB 
DRUG:	 APOMORPHINE 
HEADER	
HEADER	
HEADER	#### Hydroxocobalamin %%%%
HEADER	#### Hydroxycarbamide %%%%
DRUG:	 CLOZAPINE  
DRUG:	 STAVUDINE 
HEADER	#### Hydroxychloroquine %%%%
DRUG:	 AMIODARONE 
DRUG:	 MOXIFLOXACIN 
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
DRUG:	 MEFLOQUINE 
DRUG:	 DROPERIDOL 
DRUG:	 DIGOXIN 
DRUG:	 CICLOSPORIN  
DRUG:	 BOSUTINIB 
HEADER	#### Ibrutinib %%%%
DRUG:	 DRONEDARONE 
DRUG:	 CLARITHROMYCIN 
DRUG:	 RIFAMPICIN 
DRUG:	 FOSPHENYTOIN  
HEADER	#### Ibrutinib %%%%
DRUG:	 PHENYTOIN 
DRUG:	 ITRACONAZOLE  
DRUG:	 VORICONAZOLE 
DRUG:	 CLOZAPINE  
DRUG:	 FOSAMPRENAVIR 
DRUG:	 SAQUINAVIR 
DRUG:	 APREPITANT 
DRUG:	 VERAPAMIL 
DRUG:	 COBICISTAT 
DRUG:	 IMATINIB 
HEADER	
HEADER	#### Idarubicin %%%%
DRUG:	 CLOZAPINE  
DRUG:	 CICLOSPORIN 
HEADER	#### Idelalisib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 FOSPHENYTOIN  
DRUG:	 PHENYTOIN 
DRUG:	 QUETIAPINE 
HEADER	#### Ifosfamide %%%%
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
HEADER	#### Iloprost %%%%
HEADER	#### Imatinib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 OXCARBAZEPINE  
DRUG:	 PHENYTOIN 
DRUG:	 CLOZAPINE  
DRUG:	 BOCEPREVIR 
DRUG:	 IBRUTINIB 
HEADER	
HEADER	#### Imipenem with Cilastatin %%%%
DRUG:	 VALPROIC ACID 
DRUG:	 VALGANCICLOVIR 
HEADER	
HEADER	#### Immunoglobulins %%%%
DRUG:	 BCG VACCINE 
DRUG:	 MMR VACCINE 
HEADER	#### Immunoglobulins %%%%
DRUG:	 YELLOW FEVER VACCINE 
HEADER	
HEADER	
HEADER	#### Indinavir %%%%
DRUG:	 AMIODARONE 
DRUG:	 FLECAINIDE  
DRUG:	 TELITHROMYCIN 
DRUG:	 FOSPHENYTOIN  
DRUG:	 PHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 KETOCONAZOLE  
DRUG:	 QUININE  
DRUG:	 ARIPIPRAZOLE  
DRUG:	 PIMOZIDE  
HEADER	#### Indinavir %%%%
DRUG:	 QUETIAPINE 
DRUG:	 SAQUINAVIR 
DRUG:	 ALPRAZOLAM 
DRUG:	 MIDAZOLAM  
DRUG:	 AVANAFIL 
DRUG:	 CICLOSPORIN 
DRUG:	 COLCHICINE  
DRUG:	 CABAZITAXEL 
DRUG:	 IBRUTINIB 
DRUG:	 PONATINIB 
DRUG:	 DOCETAXEL 
DRUG:	 ERGOTAMINE 
DRUG:	 ELETRIPTAN  
DRUG:	 ROSUVASTATIN 
DRUG:	 LOMITAPIDE  
DRUG:	 ORLISTAT 
DRUG:	 RANOLAZINE 
DRUG:	 SILDENAFIL 
DRUG:	 VARDENAFIL 
HEADER	#### Infliximab %%%%
DRUG:	 ABATACEPT 
DRUG:	 ANAKINRA 
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Interferons %%%%
DRUG:	 AMINOPHYLLINE  
DRUG:	 TELBIVUDINE 
DRUG:	 THEOPHYLLINE  
HEADER	#### Ipilimumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	
HEADER	
HEADER	#### Irinotecan %%%%
DRUG:	 ITRACONAZOLE 
DRUG:	 CLOZAPINE  
DRUG:	 ATAZANAVIR  
DRUG:	 SORAFENIB 
HEADER	#### Iron Salts %%%%
HEADER	
HEADER	#### Isoniazid %%%%
DRUG:	 CYCLOSERINE 
DRUG:	 CARBAMAZEPINE  
DRUG:	 PHENYTOIN  
HEADER	
HEADER	#### Ivabradine %%%%
DRUG:	 DISOPYRAMIDE 
DRUG:	 ERYTHROMYCIN 
DRUG:	 FLUCONAZOLE 
HEADER	#### Ivabradine %%%%
DRUG:	 ITRACONAZOLE 
DRUG:	 MEFLOQUINE 
DRUG:	 PIMOZIDE 
DRUG:	 RITONAVIR 
DRUG:	 SOTALOL 
DRUG:	 VERAPAMIL 
DRUG:	 PENTAMIDINE ISETIONATE 
HEADER	#### Ivacaftor %%%%
DRUG:	 ERYTHROMYCIN  
DRUG:	 RIFAMPICIN 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 KETOCONAZOLE  
DRUG:	 VORICONAZOLE  
HEADER	#### Ivermectin %%%%
HEADER	
HEADER	#### Kaolin %%%%
HEADER	
HEADER	
HEADER	
HEADER	#### Lacosamide %%%%
DRUG:	 TRICYCLIC-RELATED ANTIDEPRESSANTS  
HEADER	#### Lacosamide %%%%
DRUG:	 SSRIS 
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	#### Lactulose %%%%
HEADER	#### Lamivudine %%%%
DRUG:	 CLADRIBINE 
DRUG:	 ORLISTAT 
HEADER	#### Lamotrigine %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 TRICYCLICS  
DRUG:	 PHENYTOIN  
DRUG:	 VALPROIC ACID  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 OESTROGENS 
DRUG:	 ORLISTAT 
HEADER	#### Lanreotide %%%%
HEADER	
HEADER	#### Lanthanum %%%%
HEADER	#### Lapatinib %%%%
DRUG:	 RIFAMPICIN  
DRUG:	 TELITHROMYCIN 
DRUG:	 REPAGLINIDE 
DRUG:	 PHENYTOIN 
DRUG:	 VORICONAZOLE 
DRUG:	 PIMOZIDE 
DRUG:	 SAQUINAVIR 
DRUG:	 IRINOTECAN 
DRUG:	 GRAPEFRUIT JUICE 
HEADER	#### Laronidase %%%%
HEADER	#### Leflunomide %%%%
DRUG:	 METHOTREXATE 
DRUG:	 VACCINES 
HEADER	#### Lenalidomide %%%%
DRUG:	 CLARITHROMYCIN  
DRUG:	 KETOCONAZOLE  
DRUG:	 VERAPAMIL  
DRUG:	 CICLOSPORIN  
HEADER	
HEADER	#### Leukotriene Receptor Antagonists %%%%
HEADER	#### Levamisole %%%%
DRUG:	 WARFARIN 
HEADER	#### Levetiracetam %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	
HEADER	#### Levobupivacaine %%%%
HEADER	#### Levocarnitine %%%%
HEADER	
HEADER	#### Levodopa %%%%
DRUG:	 VOLATILE LIQUID GENERAL ANAESTHETICS 
DRUG:	 MOCLOBEMIDE 
HEADER	#### Lidocaine %%%%
DRUG:	 ANTI-ARRHYTHMICS 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 FOSAMPRENAVIR 
DRUG:	 SAQUINAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 PROPRANOLOL 
DRUG:	 THIAZIDES AND RELATED DIURETICS 
DRUG:	 CIMETIDINE  
HEADER	
HEADER	#### Linezolid %%%%
HEADER	
HEADER	#### Lipegfilgrastim %%%%
HEADER	
HEADER	
HEADER	#### Lithium %%%%
DRUG:	 ACE INHIBITORS  
DRUG:	 KETOROLAC  
DRUG:	 ANGIOTENSIN-II RECEPTOR ANTAGONISTS  
DRUG:	 AMIODARONE  
DRUG:	 TRICYCLICS 
DRUG:	 PHENOTHIAZINES 
DRUG:	 SULPIRIDE 
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 DAPOXETINE  
DRUG:	 LOOP DIURETICS  
DRUG:	 POTASSIUM- SPARING DIURETICS AND ALDOSTERONE ANTAGONISTS  
DRUG:	 METHYLDOPA  
HEADER	
HEADER	
HEADER	#### Lofexidine %%%%
HEADER	#### Lomitapide %%%%
DRUG:	 DRONEDARONE  
DRUG:	 TELITHROMYCIN 
DRUG:	 TRIAZOLES  
DRUG:	 SAQUINAVIR 
DRUG:	 TIPRANAVIR  
DRUG:	 VERAPAMIL  
DRUG:	 SIMVASTATIN  
DRUG:	 BILE ACID SEQUESTRANTS  
HEADER	#### Lomustine %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Loperamide %%%%
HEADER	#### Lopinavir %%%%
DRUG:	 LIDOCAINE 
DRUG:	 TELITHROMYCIN 
DRUG:	 PRIMIDONE 
DRUG:	 ARIPIPRAZOLE  
DRUG:	 QUETIAPINE 
DRUG:	 DARUNAVIR 
DRUG:	 EFAVIRENZ 
DRUG:	 TENOFOVIR 
DRUG:	 TIPRANAVIR 
DRUG:	 BOSENTAN  
DRUG:	 RUXOLITINIB 
DRUG:	 LOMITAPIDE  
DRUG:	 ORLISTAT 
DRUG:	 RANOLAZINE 
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	#### Macitentan %%%%
DRUG:	 RIFAMPICIN 
HEADER	#### Macrogols %%%%
HEADER	#### Macrolides %%%%
DRUG:	 AMINOPHYLLINE  
DRUG:	 DRONEDARONE  
DRUG:	 RIFABUTIN  
DRUG:	 BEDAQUILINE 
HEADER	#### Macrolides %%%%
DRUG:	 RIFAMYCINS 
DRUG:	 DABIGATRAN 
DRUG:	 TRAZODONE 
DRUG:	 VALPROIC ACID  
DRUG:	 ITRACONAZOLE 
DRUG:	 LORATADINE 
DRUG:	 MIZOLASTINE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 LURASIDONE  
DRUG:	 PIMOZIDE 
DRUG:	 QUETIAPINE 
DRUG:	 SULPIRIDE 
DRUG:	 ATAZANAVIR 
DRUG:	 EFAVIRENZ 
HEADER	#### Macrolides %%%%
DRUG:	 RITONAVIR  
DRUG:	 SIMEPREVIR 
DRUG:	 SIMEPREVIR 
DRUG:	 TELAPREVIR  
DRUG:	 ZIDOVUDINE  
DRUG:	 ZOPICLONE 
DRUG:	 ATOMOXETINE 
DRUG:	 AVANAFIL 
DRUG:	 LERCANIDIPINE 
DRUG:	 CICLOSPORIN  
DRUG:	 CILOSTAZOL  
DRUG:	 CLOPIDOGREL 
DRUG:	 COLCHICINE  
DRUG:	 AXITINIB  
HEADER	#### Macrolides %%%%
DRUG:	 CABOZANTINIB 
DRUG:	 IBRUTINIB 
DRUG:	  PONATINIB 
DRUG:	 CABAZITAXEL 
DRUG:	 VINORELBINE 
DRUG:	 EPLERENONE  
DRUG:	 DOMPERIDONE  
DRUG:	 ERGOTAMINE 
DRUG:	 ELETRIPTAN  
DRUG:	 IVABRADINE 
DRUG:	 IVACAFTOR  
DRUG:	 LENALIDOMIDE  
DRUG:	 PRAVASTATIN 
HEADER	#### Macrolides %%%%
DRUG:	 LOMITAPIDE  
DRUG:	 PENTAMIDINE ISETIONATE 
DRUG:	 RANOLAZINE 
DRUG:	 SILDENAFIL 
DRUG:	 SIROLIMUS 
DRUG:	 SIROLIMUS 
DRUG:	 TACROLIMUS 
DRUG:	 THEOPHYLLINE  
DRUG:	 TICAGRELOR 
HEADER	#### Magnesium (parenteral) %%%%
DRUG:	 NIFEDIPINE  
HEADER	
HEADER	#### Mannitol %%%%
HEADER	#### MAOIs %%%%
DRUG:	 ALCOHOL  
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 FENTANYL 
DRUG:	 PETHIDINE 
DRUG:	 OPIOID ANALGESICS 
DRUG:	 SERTRALINE  
DRUG:	 DULOXETINE  
DRUG:	 MAOIS  
DRUG:	 TRICYCLICS 
DRUG:	 ANTIEPILEPTICS  
HEADER	#### MAOIs %%%%
DRUG:	 CARBAMAZEPINE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 CLOZAPINE 
DRUG:	 BUSPIRONE  
DRUG:	 ATOMOXETINE 
DRUG:	 BUPROPION 
DRUG:	 DAPOXETINE  
DRUG:	 LEVODOPA 
DRUG:	 TOLCAPONE 
DRUG:	 ZOLMITRIPTAN  
DRUG:	 METHYLDOPA 
DRUG:	 DOBUTAMINE 
DRUG:	 NORADRENALINE (NOREPINEPHRINE)  
DRUG:	 ISOMETHEPTENE 
HEADER	#### MAOIs %%%%
DRUG:	 METHYLPHENIDATE 
DRUG:	 PSEUDOEPHEDRINE 
DRUG:	 OXYMETAZOLINE 
DRUG:	 TETRABENAZINE  
HEADER	
HEADER	#### Maraviroc %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 KETOCONAZOLE  
DRUG:	 INDINAVIR 
DRUG:	 RITONAVIR 
DRUG:	 COBICISTAT  
DRUG:	 ORLISTAT 
HEADER	#### Mebendazole %%%%
HEADER	
HEADER	
HEADER	#### Mefloquine %%%%
DRUG:	 AMIODARONE 
DRUG:	 MOXIFLOXACIN 
DRUG:	 RIFAMPICIN 
DRUG:	 ANTIEPILEPTICS 
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
DRUG:	 QUININE  
DRUG:	 RISPERIDONE 
DRUG:	 ATOMOXETINE 
DRUG:	 IVABRADINE 
HEADER	
HEADER	
HEADER	
HEADER	#### Melphalan %%%%
DRUG:	 CLOZAPINE  
DRUG:	 CICLOSPORIN 
HEADER	#### Memantine %%%%
DRUG:	 KETAMINE  
DRUG:	 DEXTROMETHORPHAN  
DRUG:	 AMANTADINE  
HEADER	
HEADER	#### Mepacrine %%%%
DRUG:	 ALLOPURINOL  
DRUG:	 TRIMETHOPRIM  
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
DRUG:	 FEBUXOSTAT 
HEADER	#### Meropenem %%%%
DRUG:	 VALPROIC ACID 
HEADER	#### Methenamine %%%%
DRUG:	 SULFONAMIDES 
DRUG:	 ACETAZOLAMIDE 
HEADER	
HEADER	#### Methotrexate %%%%
DRUG:	 NITROUS OXIDE 
DRUG:	 DICLOFENAC 
DRUG:	 MELOXICAM  
DRUG:	 NAPROXEN  
DRUG:	 CIPROFLOXACIN  
DRUG:	 TRIMETHOPRIM  
DRUG:	 PYRIMETHAMINE 
DRUG:	 CLOZAPINE  
DRUG:	 CICLOSPORIN 
DRUG:	 CISPLATIN 
DRUG:	 LEFLUNOMIDE 
DRUG:	 ACITRETIN  
HEADER	#### Methyldopa %%%%
DRUG:	 MAOIS 
DRUG:	 LITHIUM  
DRUG:	 SALBUTAMOL 
HEADER	#### Methylthioninium %%%%
DRUG:	 SSRIS  
DRUG:	 MIRTAZAPINE 
DRUG:	 BUSPIRONE 
HEADER	#### Methylthioninium %%%%
DRUG:	 BUPROPION 
HEADER	#### Metoclopramide %%%%
DRUG:	 CICLOSPORIN 
HEADER	#### Metronidazole %%%%
DRUG:	 COUMARINS 
DRUG:	 TEGAFUR  
HEADER	
HEADER	#### Micafungin %%%%
HEADER	#### Mifamurtide %%%%
HEADER	#### Mifepristone %%%%
HEADER	
HEADER	
HEADER	
HEADER	#### Mirabegron %%%%
HEADER	#### Mirtazapine %%%%
DRUG:	 ALCOHOL 
DRUG:	 MOCLOBEMIDE  
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 METHYLTHIONINIUM 
HEADER	#### Mitomycin %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Mitotane %%%%
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
HEADER	#### Mitoxantrone %%%%
DRUG:	 CLOZAPINE  
DRUG:	 OPIOID ANALGESICS 
DRUG:	 FLUVOXAMINE 
DRUG:	 TRICYCLIC- 
DRUG:	 DULOXETINE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 BUPROPION 
DRUG:	 CLOPIDOGREL 
DRUG:	 SELEGILINE 
DRUG:	 ZOLMITRIPTAN  
DRUG:	 SYMPATHOMIMETICS 
HEADER	#### Modafinil %%%%
DRUG:	 CICLOSPORIN 
DRUG:	 BOSUTINIB 
DRUG:	 OESTROGENS  
HEADER	
HEADER	
HEADER	
HEADER	#### Moxisylyte %%%%
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 BETA-BLOCKERS 
HEADER	#### Moxonidine %%%%
HEADER	#### Muscle Relaxants %%%%
DRUG:	 VOLATILE LIQUID GENERAL ANAESTHETICS 
DRUG:	 CLINDAMYCIN 
DRUG:	 POLYMYXINS 
DRUG:	 VANCOMYCIN 
DRUG:	 TRICYCLICS 
DRUG:	 CARBAMAZEPINE  
DRUG:	 PHENYTOIN  
HEADER	#### Muscle Relaxants %%%%
HEADER	#### Mycophenolate %%%%
DRUG:	 RIFAMPICIN 
HEADER	#### Mycophenolate %%%%
HEADER	#### Nalmefene %%%%
DRUG:	  Naproxen  
HEADER	
HEADER	#### Natalizumub %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Nefopam %%%%
DRUG:	 TRICYCLICS 
HEADER	#### Nevirapine %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 WARFARIN 
DRUG:	 FLUCONAZOLE 
DRUG:	 ITRACONAZOLE 
DRUG:	 ARIPIPRAZOLE  
DRUG:	 FOSAMPRENAVIR 
HEADER	#### Nevirapine %%%%
DRUG:	 ZIDOVUDINE 
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
HEADER	
HEADER	#### Nicorandil %%%%
DRUG:	 AVANAFIL  
DRUG:	 SILDENAFIL  
DRUG:	 TADALAFIL  
DRUG:	 VARDENAFIL 
HEADER	#### Nicotine %%%%
HEADER	#### Nicotinic Acid %%%%
DRUG:	 STATINS  
HEADER	
HEADER	#### Nilotinib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 VORICONAZOLE 
DRUG:	 CLOZAPINE  
DRUG:	 RITONAVIR 
DRUG:	 GRAPEFRUIT JUICE 
HEADER	
HEADER	#### Nintedanib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 KETOCONAZOLE 
HEADER	#### Nitrates %%%%
DRUG:	 HEPARINS 
DRUG:	 AVANAFIL  
DRUG:	 RIOCIGUAT 
DRUG:	 SILDENAFIL  
DRUG:	 TADALAFIL  
DRUG:	 VARDENAFIL 
HEADER	
HEADER	#### Nitrofurantoin %%%%
HEADER	
HEADER	
HEADER	
HEADER	#### Norepinephrine %%%%
HEADER	
HEADER	#### NSAIDs %%%%
DRUG:	 ASPIRIN 
DRUG:	 QUINOLONES 
DRUG:	 ANTICOAGULANTS  
DRUG:	 HEPARINS 
DRUG:	 VENLAFAXINE 
DRUG:	 SULFONYLUREAS 
DRUG:	 ZIDOVUDINE 
DRUG:	 CICLOSPORIN  
DRUG:	 REGORAFENIB 
DRUG:	 DIMETHYL SULFOXIDE 
DRUG:	 POTASSIUM-SPARING DIURETICS AND ALDOSTERONE 
DRUG:	 POTASSIUM-SPARING DIURETICS AND ALDOSTERONE ANTAGONISTS 
DRUG:	 LITHIUM  
DRUG:	 PENTOXIFYLLINE  
DRUG:	 TACROLIMUS 
HEADER	#### Obinutuzumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Octreotide %%%%
DRUG:	 CICLOSPORIN 
HEADER	#### Oestrogens %%%%
DRUG:	 RIFAMYCINS  
DRUG:	 PHENINDIONE 
DRUG:	 TRICYCLICS  
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 VALPROIC ACID 
DRUG:	 ATAZANAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 APREPITANT  
DRUG:	 BOSENTAN  
DRUG:	 COBICISTAT  
DRUG:	 VEMURAFENIB 
DRUG:	 DABRAFENIB  
DRUG:	 SELEGILINE 
DRUG:	 FOSAPREPITANT  
DRUG:	 MODAFINIL  
HEADER	
HEADER	#### Ofatumumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	#### Opioid Analgesics %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 TELITHROMYCIN 
DRUG:	 TELITHROMYCIN 
DRUG:	 COUMARINS 
DRUG:	 PAROXETINE  
DRUG:	 MAOIS 
DRUG:	 MOCLOBEMIDE 
DRUG:	 TRICYCLICS 
DRUG:	 PRIMIDONE 
DRUG:	 GABAPENTIN 
DRUG:	 FLUCONAZOLE  
DRUG:	 ITRACONAZOLE 
HEADER	#### Opioid Analgesics %%%%
DRUG:	 TRIAZOLES 
DRUG:	 SEDATING ANTIHISTAMINES 
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 AMISULPRIDE 
DRUG:	 RITONAVIR 
DRUG:	 ZIDOVUDINE 
DRUG:	 ATOMOXETINE 
DRUG:	 BOSUTINIB 
DRUG:	 VANDETANIB 
DRUG:	 DAPOXETINE  
DRUG:	 SELEGILINE  
DRUG:	 MEMANTINE  
DRUG:	 NALMEFENE 
DRUG:	 SODIUM OXYBATE  
HEADER	#### Oritavancin %%%%
HEADER	#### Orlistat %%%%
DRUG:	 ANTIEPILEPTICS 
DRUG:	 ABACAVIR 
DRUG:	 EFAVIRENZ 
DRUG:	 ETRAVIRINE 
DRUG:	 TENOFOVIR 
DRUG:	 ZIDOVUDINE 
DRUG:	 CICLOSPORIN 
HEADER	#### Oxcarbazepine %%%%
DRUG:	 TRICYCLICS  
DRUG:	 PRIMIDONE 
DRUG:	 PERAMPANEL  
DRUG:	 VALPROIC ACID 
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 SIMEPREVIR 
HEADER	#### Oxcarbazepine %%%%
DRUG:	 RILPIVIRINE  
DRUG:	 CLOPIDOGREL 
DRUG:	 IMATINIB 
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
HEADER	#### Oxytocin %%%%
HEADER	#### Paclitaxel %%%%
DRUG:	 CLOZAPINE  
DRUG:	 LAPATINIB 
HEADER	#### Pancreatin %%%%
HEADER	
HEADER	#### Panitumumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Paracetamol %%%%
HEADER	#### Paraldehyde %%%%
DRUG:	 ALCOHOL 
DRUG:	 DISULFIRAM 
HEADER	#### Parasympathomimetics %%%%
DRUG:	 CLINDAMYCIN 
DRUG:	 POLYMYXINS 
HEADER	
HEADER	
HEADER	
HEADER	#### Pasireotide %%%%
DRUG:	 CICLOSPORIN 
HEADER	#### Pazopanib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 KETOCONAZOLE  
DRUG:	 VORICONAZOLE  
DRUG:	 CLOZAPINE  
DRUG:	 BOCEPREVIR 
DRUG:	 SAQUINAVIR 
DRUG:	 GRAPEFRUIT JUICE 
HEADER	#### Pegfilgrastim %%%%
HEADER	
HEADER	#### Pemetrexed %%%%
DRUG:	 PYRIMETHAMINE 
DRUG:	 CLOZAPINE  
HEADER	#### Penicillamine %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Penicillins %%%%
DRUG:	 VALPROIC ACID 
HEADER	#### Pentamidine Isetionate %%%%
DRUG:	 AMIODARONE 
DRUG:	 DISOPYRAMIDE 
DRUG:	 MOXIFLOXACIN 
HEADER	#### Pentamidine Isetionate %%%%
DRUG:	 DELAMANID 
DRUG:	 TELITHROMYCIN 
DRUG:	 ESCITALOPRAM  
DRUG:	 TRICYCLICS 
DRUG:	 ARTENIMOL WITH PIPERAQUINE  
DRUG:	 AMISULPRIDE  
DRUG:	 PHENOTHIAZINES 
DRUG:	 SAQUINAVIR 
DRUG:	 VANDETANIB 
DRUG:	 IVABRADINE 
HEADER	
HEADER	#### Pentostatin %%%%
DRUG:	 CLOZAPINE  
DRUG:	 FLUDARABINE  
HEADER	#### Pentoxifylline %%%%
DRUG:	 KETOROLAC  
HEADER	#### Perampanel %%%%
DRUG:	 TRICYCLICS  
DRUG:	 OXCARBAZEPINE  
DRUG:	 TOPIRAMATE 
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
HEADER	#### Pergolide %%%%
HEADER	#### Pertuzumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Phenindione %%%%
DRUG:	 ALCOHOL 
DRUG:	 ANABOLIC STEROIDS 
DRUG:	 DICLOFENAC  
DRUG:	 ASPIRIN  
DRUG:	 DRONEDARONE 
DRUG:	 TETRACYCLINES 
DRUG:	 SULFONAMIDES 
DRUG:	 RIVAROXABAN  
DRUG:	 RITONAVIR 
DRUG:	 CLOPIDOGREL 
DRUG:	 DIPYRIDAMOLE 
DRUG:	 ENTERAL FEEDS  
DRUG:	 FIBRATES 
DRUG:	 OESTROGENS 
DRUG:	 PROGESTOGENS 
DRUG:	 TESTOLACTONE 
DRUG:	 TESTOSTERONE 
DRUG:	 THYROID HORMONES 
DRUG:	 VITAMIN K 
HEADER	#### Phenobarbital %%%%
DRUG:	 AMINOPHYLLINE  
DRUG:	 PRAZIQUANTEL 
DRUG:	 PROPAFENONE 
DRUG:	 TELITHROMYCIN  
DRUG:	 COUMARINS  
DRUG:	 RIVAROXABAN 
DRUG:	 TRICYCLIC-RELATED ANTIDEPRESSANTS 
DRUG:	 TRICYCLICS  
DRUG:	 STIRIPENTOL 
DRUG:	 POSACONAZOLE 
HEADER	#### Phenobarbital %%%%
DRUG:	 GRISEOFULVIN  
DRUG:	 MEFLOQUINE 
DRUG:	 LURASIDONE 
DRUG:	 SAQUINAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 ISRADIPINE 
DRUG:	 NIMODIPINE  
DRUG:	 CANNABIS EXTRACT 
DRUG:	 CICLOSPORIN  
DRUG:	 COBICISTAT 
DRUG:	 CORTICOSTEROIDS  
DRUG:	 PONATINIB 
DRUG:	 IRINOTECAN  
HEADER	#### Phenobarbital %%%%
DRUG:	 PROCARBAZINE 
DRUG:	 CARBONIC ANHYDRASE INHIBITORS 
DRUG:	 TOREMIFENE  
DRUG:	 IVACAFTOR 
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
DRUG:	 TACROLIMUS 
DRUG:	 THEOPHYLLINE  
DRUG:	 ULIPRISTAL  
HEADER	#### Phenytoin %%%%
DRUG:	 AMINOPHYLLINE 
DRUG:	 ASPIRIN 
HEADER	#### Phenytoin %%%%
DRUG:	 PARACETAMOL  
DRUG:	 LEVAMISOLE 
DRUG:	 DRONEDARONE 
DRUG:	 BEDAQUILINE 
DRUG:	 ISONIAZID  
DRUG:	 TELITHROMYCIN  
DRUG:	 TRIMETHOPRIM  
DRUG:	 RIVAROXABAN 
DRUG:	 TRICYCLICS 
DRUG:	 ESLICARBAZEPINE 
DRUG:	 ZONISAMIDE 
DRUG:	 PERAMPANEL  
DRUG:	 RETIGABINE 
HEADER	#### Phenytoin %%%%
DRUG:	 VIGABATRIN 
DRUG:	 CASPOFUNGIN 
DRUG:	 MEFLOQUINE 
DRUG:	 PYRIMETHAMINE 
DRUG:	 LURASIDONE 
DRUG:	 SAQUINAVIR 
DRUG:	 ZIDOVUDINE 
DRUG:	 NIMODIPINE  
HEADER	#### Phenytoin %%%%
DRUG:	 DILTIAZEM  
DRUG:	 CANNABIS EXTRACT 
DRUG:	 CICLOSPORIN  
DRUG:	 COBICISTAT 
DRUG:	 CORTICOSTEROIDS  
DRUG:	 BORTEZOMIB 
DRUG:	 IDELALISIB  
DRUG:	 CABOZANTINIB 
DRUG:	 LAPATINIB  
DRUG:	 PROCARBAZINE 
DRUG:	 DEXRAZOXANE 
DRUG:	 DISULFIRAM  
DRUG:	 FUROSEMIDE 
DRUG:	 CARBONIC ANHYDRASE INHIBITORS 
DRUG:	 TOREMIFENE 
DRUG:	 IVACAFTOR 
DRUG:	 NON-DEPOLARISING MUSCLE RELAXANTS  
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
DRUG:	 SULFINPYRAZONE 
DRUG:	 THEOPHYLLINE 
DRUG:	 SUCRALFATE 
DRUG:	 ULIPRISTAL  
HEADER	#### Pholcodine %%%%
HEADER	#### Phosphodiesterase Type-3 Inhibitors %%%%
DRUG:	 ANAGRELIDE 
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	#### Pirfenidone %%%%
DRUG:	 CIPROFLOXACIN 
DRUG:	 FLUVOXAMINE 
HEADER	#### Pixantrone %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Pizotifen %%%%
HEADER	#### Platinum Compounds %%%%
DRUG:	 ALDESLEUKIN 
DRUG:	 VANCOMYCIN 
DRUG:	 CLOZAPINE  
DRUG:	 METHOTREXATE 
HEADER	#### Polymyxins %%%%
DRUG:	 CICLOSPORIN 
DRUG:	 PLATINUM COMPOUNDS 
DRUG:	 LOOP DIURETICS 
DRUG:	 NON- 
DRUG:	 SUXAMETHONIUM 
DRUG:	 PYRIDOSTIGMINE 
HEADER	
HEADER	#### Polystyrene Sulfonate Resins %%%%
HEADER	#### Pomalidomide %%%%
DRUG:	 FLUVOXAMINE 
HEADER	#### Ponatinib %%%%
DRUG:	 TELITHROMYCIN 
DRUG:	 RIFAMPICIN 
DRUG:	 CLOZAPINE  
HEADER	#### Potassium Aminobenzoate %%%%
HEADER	#### Potassium Salts %%%%
DRUG:	 ACE INHIBITORS 
DRUG:	 ANGIOTENSIN-II RECEPTOR ANTAGONISTS 
DRUG:	 CICLOSPORIN 
DRUG:	 POTASSIUM-SPARING DIURETICS AND ALDOSTERONE ANTAGONISTS 
DRUG:	 TACROLIMUS 
HEADER	#### Pramipexole %%%%
HEADER	#### Prasugrel %%%%
HEADER	
HEADER	#### Praziquantel %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 PHENOBARBITAL 
DRUG:	 PRIMIDONE 
DRUG:	 CHLOROQUINE 
HEADER	#### Pregabalin %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	#### Prilocaine %%%%
HEADER	#### Primaquine %%%%
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
HEADER	#### Primidone %%%%
DRUG:	 AMINOPHYLLINE  
DRUG:	 PRAZIQUANTEL 
DRUG:	 PROPAFENONE 
DRUG:	 DOXYCYCLINE  
DRUG:	 TELITHROMYCIN  
DRUG:	 COUMARINS  
DRUG:	 RIVAROXABAN 
DRUG:	 MIANSERIN  
HEADER	#### Primidone %%%%
DRUG:	 TRICYCLIC-RELATED ANTIDEPRESSANTS 
DRUG:	 TRICYCLICS  
DRUG:	 STIRIPENTOL 
DRUG:	 GRISEOFULVIN  
DRUG:	 MEFLOQUINE 
DRUG:	 LURASIDONE 
DRUG:	 INDINAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 NIMODIPINE  
DRUG:	 CANNABIS EXTRACT 
DRUG:	 CICLOSPORIN  
DRUG:	 COBICISTAT 
DRUG:	 CORTICOSTEROIDS  
DRUG:	 PONATINIB 
DRUG:	 PROCARBAZINE 
DRUG:	 CARBONIC ANHYDRASE INHIBITORS 
DRUG:	 TOREMIFENE  
DRUG:	 IVACAFTOR 
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
DRUG:	 TACROLIMUS 
DRUG:	 THEOPHYLLINE  
DRUG:	 ULIPRISTAL  
HEADER	#### Procarbazine %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Progestogens %%%%
DRUG:	 RIFAMYCINS  
DRUG:	 PHENINDIONE 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PHENOBARBITAL 
DRUG:	 TOPIRAMATE 
DRUG:	 LAMOTRIGINE 
DRUG:	 ATAZANAVIR 
DRUG:	 BOCEPREVIR  
DRUG:	 NEVIRAPINE  
DRUG:	 APREPITANT  
DRUG:	 BOSENTAN  
DRUG:	 VEMURAFENIB 
DRUG:	 DABRAFENIB  
DRUG:	 SELEGILINE 
DRUG:	 FOSAPREPITANT  
DRUG:	 ULIPRISTAL 
HEADER	#### Proguanil %%%%
DRUG:	 PYRIMETHAMINE 
HEADER	#### Propafenone %%%%
DRUG:	 ANTI-ARRHYTHMICS 
DRUG:	 RIFAMPICIN  
DRUG:	 COUMARINS 
DRUG:	 TRICYCLICS 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 SAQUINAVIR 
HEADER	#### Propafenone %%%%
DRUG:	 TELAPREVIR  
DRUG:	 PROPRANOLOL 
DRUG:	 DIGOXIN  
DRUG:	 CIMETIDINE 
HEADER	#### Prostaglandins %%%%
HEADER	
HEADER	#### Proton Pump Inhibitors %%%%
DRUG:	 COUMARINS 
DRUG:	 PHENYTOIN 
DRUG:	 POSACONAZOLE 
HEADER	#### Proton Pump Inhibitors %%%%
DRUG:	 VORICONAZOLE  
DRUG:	 TIPRANAVIR 
DRUG:	 CILOSTAZOL  
DRUG:	 CLOPIDOGREL 
DRUG:	 LAPATINIB 
DRUG:	 PAZOPANIB 
HEADER	
HEADER	#### Pyrazinamide %%%%
HEADER	
HEADER	
HEADER	#### Pyrimethamine %%%%
DRUG:	 TRIMETHOPRIM 
DRUG:	 PHENYTOIN 
DRUG:	 PROGUANIL 
DRUG:	 PEMETREXED 
HEADER	
HEADER	#### Quinagolide %%%%
HEADER	
HEADER	#### Quinine %%%%
DRUG:	 FLECAINIDE 
DRUG:	 RIFAMPICIN 
DRUG:	 ESCITALOPRAM 
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
DRUG:	 MEFLOQUINE  
DRUG:	 RISPERIDONE 
DRUG:	 INDINAVIR 
DRUG:	 SAQUINAVIR 
DRUG:	 DIGOXIN 
HEADER	#### Quinolones %%%%
DRUG:	 AMINOPHYLLINE 
DRUG:	 AMINOPHYLLINE 
DRUG:	 NSAIDS 
DRUG:	 AMIODARONE 
DRUG:	 DISOPYRAMIDE 
DRUG:	 ERYTHROMYCIN 
HEADER	#### Quinolones %%%%
DRUG:	 NITROFURANTOIN 
DRUG:	 TELITHROMYCIN 
DRUG:	 PHENINDIONE 
DRUG:	 TRICYCLICS 
DRUG:	 MIZOLASTINE 
DRUG:	 HYDROXYCHLOROQUINE 
DRUG:	 QUININE 
DRUG:	 BENPERIDOL 
DRUG:	 PIMOZIDE 
DRUG:	 OLANZAPINE 
DRUG:	 SAQUINAVIR 
DRUG:	 ATOMOXETINE 
DRUG:	 SOTALOL 
DRUG:	 CICLOSPORIN 
DRUG:	 CLOPIDOGREL 
DRUG:	 METHOTREXATE  
DRUG:	 IBRUTINIB 
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 TIZANIDINE  
DRUG:	 PENTAMIDINE ISETIONATE 
DRUG:	 PIRFENIDONE 
DRUG:	 THEOPHYLLINE 
HEADER	
HEADER	
HEADER	#### Raloxifene %%%%
HEADER	#### Raltegravir %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 FOSAMPRENAVIR 
DRUG:	 ORLISTAT 
HEADER	#### Raltitrexed %%%%
DRUG:	 CLOZAPINE  
DRUG:	 FOLATES 
HEADER	
HEADER	
HEADER	#### Ranolazine %%%%
DRUG:	 DISOPYRAMIDE 
DRUG:	 TELITHROMYCIN 
DRUG:	 RIFAMPICIN 
DRUG:	 KETOCONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 SAQUINAVIR  
DRUG:	 TIPRANAVIR 
DRUG:	 SOTALOL 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 SIMVASTATIN  
DRUG:	 LOMITAPIDE 
DRUG:	 TACROLIMUS 
HEADER	#### Rasagiline %%%%
DRUG:	 PETHIDINE  
DRUG:	 MAOIS 
DRUG:	 TRICYCLICS 
DRUG:	 SYMPATHOMIMETICS 
HEADER	#### Reboxetine %%%%
DRUG:	 MACROLIDES 
DRUG:	 MAOIS  
DRUG:	 TRIAZOLES 
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
HEADER	#### Regorafenib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 WARFARIN 
DRUG:	 KETOCONAZOLE 
DRUG:	 CLOZAPINE  
HEADER	#### Retigabine %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	#### Retinoids %%%%
DRUG:	 ALCOHOL  
DRUG:	 TETRACYCLINES  
DRUG:	 COUMARINS 
DRUG:	 KETOCONAZOLE  
DRUG:	 VORICONAZOLE 
DRUG:	 METHOTREXATE  
DRUG:	 VITAMIN A 
HEADER	#### Ribavirin %%%%
DRUG:	 ABACAVIR 
DRUG:	 ZIDOVUDINE 
DRUG:	 AZATHIOPRINE 
HEADER	#### Rifamycins %%%%
DRUG:	 PRAZIQUANTEL 
DRUG:	 DRONEDARONE 
DRUG:	 PROPAFENONE  
DRUG:	 TELITHROMYCIN  
DRUG:	 RIVAROXABAN 
DRUG:	 SULFONYLUREAS  
DRUG:	 PHENYTOIN  
DRUG:	 PRIMIDONE 
DRUG:	 KETOCONAZOLE  
DRUG:	 ITRACONAZOLE 
DRUG:	 POSACONAZOLE  
DRUG:	 TRIAZOLES  
DRUG:	 QUININE 
DRUG:	 HALOPERIDOL  
DRUG:	 CLOZAPINE 
DRUG:	 LURASIDONE 
DRUG:	 FOSAMPRENAVIR  
DRUG:	 DACLATASVIR 
DRUG:	 RILPIVIRINE 
DRUG:	 FOSAMPRENAVIR  
DRUG:	 ZIDOVUDINE 
DRUG:	 RILPIVIRINE  
HEADER	#### Rifamycins %%%%
DRUG:	 SAQUINAVIR  
DRUG:	 TIPRANAVIR 
DRUG:	 ATOVAQUONE  
DRUG:	 BOSENTAN 
DRUG:	 NIFEDIPINE 
DRUG:	 VERAPAMIL  
DRUG:	 CANNABIS EXTRACT 
DRUG:	 CICLOSPORIN  
DRUG:	 COBICISTAT  
DRUG:	 COBICISTAT 
DRUG:	 CORTICOSTEROIDS  
DRUG:	 TRABECTEDIN 
DRUG:	 CRIZOTINIB 
DRUG:	 VANDETANIB 
HEADER	#### Rifamycins %%%%
DRUG:	 IMATINIB  
DRUG:	 VEMURAFENIB 
DRUG:	 EVEROLIMUS  
DRUG:	 ERIBULIN  
DRUG:	 TEMSIROLIMUS 
DRUG:	 VISMODEGIB  
DRUG:	 EPLERENONE 
DRUG:	 TAMOXIFEN  
DRUG:	 IVACAFTOR 
DRUG:	 MACITENTAN 
DRUG:	 MYCOPHENOLATE 
DRUG:	 NINTEDANIB 
DRUG:	 OESTROGENS  
DRUG:	 PROGESTOGENS  
DRUG:	 RANOLAZINE 
DRUG:	 ROFLUMILAST 
DRUG:	 SIROLIMUS 
DRUG:	 TACROLIMUS 
DRUG:	 TADALAFIL 
DRUG:	 TICAGRELOR 
DRUG:	 ULIPRISTAL  
HEADER	#### Rilpivirine %%%%
DRUG:	 RIFABUTIN  
DRUG:	 RIFAMPICIN 
DRUG:	 PHENYTOIN  
DRUG:	 PRIMIDONE  
DRUG:	 DEXAMETHASONE  
DRUG:	 ORLISTAT 
DRUG:	 OMEPRAZOLE 
DRUG:	 HISTAMINE H2- ANTAGONISTS  
HEADER	#### Riociguat %%%%
DRUG:	 AVANAFIL 
DRUG:	 NITRATES 
DRUG:	 SILDENAFIL 
DRUG:	 TADALAFIL 
DRUG:	 VARDENAFIL 
HEADER	
HEADER	
HEADER	#### Ritonavir %%%%
DRUG:	 ALFUZOSIN 
DRUG:	 AMINOPHYLLINE  
DRUG:	 PETHIDINE 
DRUG:	 ALBENDAZOLE 
DRUG:	 FLECAINIDE  
DRUG:	 TELITHROMYCIN 
DRUG:	 RIVAROXABAN 
DRUG:	 PHENYTOIN 
HEADER	#### Ritonavir %%%%
DRUG:	 SODIUM VALPROATE  
DRUG:	 VALPROIC ACID 
DRUG:	 FLUCONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 QUININE  
DRUG:	 FESOTERODINE 
DRUG:	 SOLIFENACIN 
DRUG:	 QUETIAPINE 
DRUG:	 MARAVIROC  
DRUG:	 TELAPREVIR 
DRUG:	 ZOLPIDEM  
DRUG:	 BUSPIRONE  
DRUG:	 AVANAFIL 
DRUG:	 BOSENTAN  
DRUG:	 LERCANIDIPINE 
DRUG:	 CICLOSPORIN 
DRUG:	 CILOSTAZOL  
DRUG:	 COLCHICINE  
DRUG:	 FLUTICASONE 
DRUG:	 AXITINIB  
DRUG:	 VINBLASTINE 
DRUG:	 VINFLUNINE 
DRUG:	 IBRUTINIB 
DRUG:	 PACLITAXEL 
DRUG:	 DAPOXETINE  
DRUG:	 EPLERENONE 
DRUG:	 DOMPERIDONE 
DRUG:	 ERGOTAMINE 
DRUG:	 ELETRIPTAN  
DRUG:	 IVABRADINE 
DRUG:	 ROSUVASTATIN 
DRUG:	 LOMITAPIDE  
DRUG:	 OESTROGENS  
DRUG:	 RANOLAZINE 
DRUG:	 SILDENAFIL 
DRUG:	 TACROLIMUS 
DRUG:	 TADALAFIL 
DRUG:	 THEOPHYLLINE   
DRUG:	 TICAGRELOR 
DRUG:	 ULIPRISTAL  
DRUG:	 VARDENAFIL 
HEADER	#### Rituximab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Rivaroxaban %%%%
DRUG:	 DICLOFENAC  
DRUG:	 KETOROLAC  
DRUG:	 RIFAMPICIN 
DRUG:	 DABIGATRAN  
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 VORICONAZOLE 
DRUG:	 TIPRANAVIR 
DRUG:	 RITONAVIR 
DRUG:	 COBICISTAT 
HEADER	
HEADER	
HEADER	
HEADER	#### Roflumilast %%%%
DRUG:	 RIFAMPICIN 
HEADER	#### Ropinirole %%%%
HEADER	#### Ropivacaine %%%%
HEADER	#### Rotigotine %%%%
HEADER	#### Rufinamide %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
HEADER	#### Rufinamide %%%%
HEADER	#### Ruxolitinib %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 FLUCONAZOLE 
DRUG:	 POSACONAZOLE  
DRUG:	 VORICONAZOLE 
DRUG:	 CLOZAPINE  
DRUG:	 INDINAVIR 
DRUG:	 TELAPREVIR 
DRUG:	 DRONEDARONE 
DRUG:	 TELITHROMYCIN  
DRUG:	 RIVAROXABAN 
DRUG:	 SSRIS 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PRIMIDONE 
DRUG:	 VORICONAZOLE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 LURASIDONE 
DRUG:	 RITONAVIR  
DRUG:	 DACLATASVIR  
DRUG:	 TELAPREVIR 
DRUG:	 MARAVIROC  
DRUG:	 TIPRANAVIR 
DRUG:	 RILPIVIRINE  
DRUG:	 APREPITANT 
DRUG:	 VERAPAMIL 
DRUG:	 CANNABIS EXTRACT 
DRUG:	 DIGOXIN 
DRUG:	 CICLOSPORIN 
DRUG:	 COBICISTAT 
DRUG:	 PONATINIB 
DRUG:	 VINFLUNINE 
DRUG:	 LAPATINIB  
DRUG:	 VANDETANIB  
DRUG:	 IRINOTECAN  
DRUG:	 DAPOXETINE  
DRUG:	 EPLERENONE 
DRUG:	 FOSAPREPITANT 
DRUG:	 ABIRATERONE 
DRUG:	 5HT1 AGONISTS 
DRUG:	 IVACAFTOR 
DRUG:	 OESTROGENS  
DRUG:	 PROGESTOGENS  
DRUG:	 TACROLIMUS 
DRUG:	 ULIPRISTAL  
HEADER	#### Saquinavir %%%%
DRUG:	 FENTANYL  
DRUG:	 METHADONE 
DRUG:	 LIDOCAINE  
DRUG:	 PROPAFENONE 
DRUG:	 CLARITHROMYCIN  
DRUG:	 MOXIFLOXACIN 
DRUG:	 RIFAMPICIN 
DRUG:	 TELITHROMYCIN  
DRUG:	 PHENOBARBITAL 
DRUG:	 PRIMIDONE 
DRUG:	 TRIAZOLES 
DRUG:	 MIZOLASTINE 
DRUG:	 QUININE 
DRUG:	 HALOPERIDOL  
DRUG:	 LURASIDONE 
DRUG:	 QUETIAPINE 
DRUG:	 DARUNAVIR 
HEADER	#### Saquinavir %%%%
DRUG:	 TIPRANAVIR 
DRUG:	 MIDAZOLAM  
DRUG:	 AVANAFIL 
DRUG:	 SOTALOL 
DRUG:	 CICLOSPORIN 
DRUG:	 CABAZITAXEL 
DRUG:	 IBRUTINIB 
DRUG:	 DOCETAXEL 
DRUG:	 DAPOXETINE  
DRUG:	 DOMPERIDONE 
DRUG:	 ERGOTAMINE 
DRUG:	 ATORVASTATIN 
DRUG:	 SIMVASTATIN  
DRUG:	 LOMITAPIDE  
DRUG:	 ORLISTAT 
DRUG:	 PENTAMIDINE ISETIONATE 
DRUG:	 RANOLAZINE 
DRUG:	 SILDENAFIL 
DRUG:	 TACROLIMUS  
DRUG:	 TADALAFIL 
DRUG:	 ESOMEPRAZOLE 
DRUG:	 RABEPRAZOLE 
DRUG:	 OMEPRAZOLE 
DRUG:	 VARDENAFIL 
HEADER	
HEADER	#### Selegiline %%%%
DRUG:	 OPIOID ANALGESICS 
DRUG:	 VENLAFAXINE 
DRUG:	 TRICYCLICS 
DRUG:	 OESTROGENS 
DRUG:	 PROGESTOGENS 
DRUG:	 DOPAMINE 
HEADER	#### Selenium %%%%
HEADER	
HEADER	#### Sildenafil %%%%
DRUG:	 ALPHA-BLOCKERS  
DRUG:	 TELITHROMYCIN 
DRUG:	 ITRACONAZOLE 
DRUG:	 RITONAVIR 
DRUG:	 TIPRANAVIR 
DRUG:	 COBICISTAT 
DRUG:	 NICORANDIL  
DRUG:	 NITRATES  
DRUG:	 RIOCIGUAT 
HEADER	#### Siltuximab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Simeprevir %%%%
DRUG:	 AMIODARONE 
DRUG:	 TELITHROMYCIN 
HEADER	#### Simeprevir %%%%
DRUG:	 RIFABUTIN 
DRUG:	 RIFAMPICIN 
DRUG:	 FOSPHENYTOIN 
DRUG:	 PHENYTOIN  
DRUG:	 PRIMIDONE 
DRUG:	 FLUCONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 RITONAVIR 
DRUG:	 COBICISTAT 
HEADER	
HEADER	#### Sirolimus %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 VORICONAZOLE 
DRUG:	 POSACONAZOLE 
DRUG:	 TELAPREVIR  
DRUG:	 VERAPAMIL 
DRUG:	 CRIZOTINIB 
DRUG:	 GRAPEFRUIT JUICE 
HEADER	#### Sodium Aurothiomalate %%%%
DRUG:	 ACE INHIBITORS 
HEADER	#### Sodium Benzoate %%%%
HEADER	
HEADER	#### Sodium Citrate %%%%
HEADER	
HEADER	
HEADER	
HEADER	#### Sodium Oxybate %%%%
DRUG:	 OPIOID ANALGESICS  
DRUG:	 VALPROIC ACID  
DRUG:	 BENZODIAZEPINES  
HEADER	#### Sodium Phenylbutyrate %%%%
HEADER	#### Sodium Stibogluconate %%%%
DRUG:	 AMPHOTERICIN 
HEADER	#### Sodium Valproate %%%%
DRUG:	 ERYTHROMYCIN  
DRUG:	 CARBAPENEMS 
DRUG:	 TRICYCLICS  
DRUG:	 ETHOSUXIMIDE 
HEADER	#### Sodium Valproate %%%%
DRUG:	 TOPIRAMATE 
DRUG:	 MEFLOQUINE 
DRUG:	 OLANZAPINE 
DRUG:	 ORLISTAT 
DRUG:	 SODIUM OXYBATE  
DRUG:	 CIMETIDINE  
HEADER	#### Sofosbuvir %%%%
DRUG:	 AMIODARONE 
HEADER	
HEADER	#### Somatropin %%%%
HEADER	#### Sorafenib %%%%
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
DRUG:	 BOCEPREVIR 
HEADER	#### Statins %%%%
DRUG:	 AMIODARONE  
DRUG:	 DRONEDARONE 
DRUG:	 CLARITHROMYCIN 
DRUG:	 TELITHROMYCIN 
DRUG:	 COUMARINS  
DRUG:	 COUMARINS 
DRUG:	 PHENYTOIN  
DRUG:	 ITRACONAZOLE 
DRUG:	 ITRACONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 VORICONAZOLE 
DRUG:	 ATAZANAVIR 
DRUG:	 ATAZANAVIR 
HEADER	#### Statins %%%%
DRUG:	 BOCEPREVIR  
DRUG:	 RITONAVIR 
DRUG:	 RITONAVIR  
DRUG:	 TIPRANAVIR  
DRUG:	 VERAPAMIL 
DRUG:	 CICLOSPORIN 
DRUG:	 CLOPIDOGREL 
DRUG:	 COBICISTAT 
DRUG:	 COLCHICINE 
DRUG:	 ELTROMBOPAG 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 DANAZOL 
DRUG:	 BEZAFIBRATE  
HEADER	#### Statins %%%%
DRUG:	 FENOFIBRATE 
DRUG:	  LOMITAPIDE 
DRUG:	 NICOTINIC ACID  
DRUG:	 RANOLAZINE  
DRUG:	 TERIFLUNOMIDE  
DRUG:	 TICAGRELOR  
HEADER	#### Stavudine %%%%
DRUG:	 ZIDOVUDINE  
DRUG:	 HYDROXYCARBAMIDE 
DRUG:	 ORLISTAT 
HEADER	#### Stiripentol %%%%
DRUG:	 TRICYCLICS  
DRUG:	 PHENOBARBITAL 
DRUG:	 PRIMIDONE 
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	
HEADER	#### Strontium Ranelate %%%%
HEADER	#### Sucralfate %%%%
HEADER	#### Sucralfate %%%%
DRUG:	 COUMARINS  
DRUG:	 FOSPHENYTOIN 
DRUG:	 PHENYTOIN 
HEADER	#### Sugammadex %%%%
HEADER	#### Sulfasalazine %%%%
HEADER	#### Sulfinpyrazone %%%%
DRUG:	 DABIGATRAN 
DRUG:	 SULFONYLUREAS 
DRUG:	 PHENYTOIN 
DRUG:	 CICLOSPORIN 
HEADER	#### Sulfonamides %%%%
DRUG:	 PRILOCAINE 
DRUG:	 METHENAMINE 
DRUG:	 PHENINDIONE 
DRUG:	 PYRIMETHAMINE 
DRUG:	 CLOZAPINE  
DRUG:	 AZATHIOPRINE 
DRUG:	 CICLOSPORIN 
DRUG:	 METHOTREXATE  
HEADER	
HEADER	
HEADER	
HEADER	
HEADER	#### Sunitinib %%%%
DRUG:	 CLOZAPINE  
DRUG:	 BOCEPREVIR 
HEADER	
HEADER	#### Sympathomimetics %%%%
DRUG:	 GUANETHIDINE 
DRUG:	 TOLAZOLINE 
DRUG:	 VOLATILE LIQUID GENERAL ANAESTHETICS 
DRUG:	 COUMARINS 
DRUG:	 MAOIS 
HEADER	#### Sympathomimetics %%%%
DRUG:	 TRICYCLICS 
DRUG:	 BETA- BLOCKERS 
DRUG:	 CLONIDINE  
DRUG:	 SELEGILINE 
DRUG:	 SELEGILINE 
DRUG:	 NORADRENALINE (NOREPINEPHRINE) 
HEADER	#### Sympathomimetics, Beta2 %%%%
DRUG:	 KETOCONAZOLE 
DRUG:	 KETOCONAZOLE  
DRUG:	 TIPRANAVIR 
HEADER	#### Sympathomimetics, Beta2 %%%%
DRUG:	 TELAPREVIR  
DRUG:	 METHYLDOPA 
HEADER	#### Tacrolimus %%%%
DRUG:	 IBUPROFEN 
DRUG:	 CHLORAMPHENICOL  
DRUG:	 VANCOMYCIN 
DRUG:	 DABIGATRAN 
DRUG:	 PRIMIDONE 
DRUG:	 KETOCONAZOLE 
DRUG:	 AMPHOTERICIN 
DRUG:	 CASPOFUNGIN 
DRUG:	 DROPERIDOL  
DRUG:	 FOSAMPRENAVIR 
DRUG:	 SAQUINAVIR  
HEADER	#### Tacrolimus %%%%
DRUG:	 TELAPREVIR  
DRUG:	 DILTIAZEM 
DRUG:	 NIFEDIPINE 
DRUG:	 CICLOSPORIN  
DRUG:	 AFATINIB 
DRUG:	 IMATINIB 
DRUG:	 POTASSIUM-SPARING DIURETICS AND ALDOSTERONE ANTAGONISTS 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 POTASSIUM SALTS 
DRUG:	 RANOLAZINE 
HEADER	#### Tadalafil %%%%
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 RIFAMPICIN 
DRUG:	 ITRACONAZOLE 
DRUG:	 TELAPREVIR 
DRUG:	 COBICISTAT 
DRUG:	 NICORANDIL  
DRUG:	 NITRATES  
DRUG:	 RIOCIGUAT 
HEADER	#### Tamoxifen %%%%
DRUG:	 COUMARINS 
DRUG:	 PAROXETINE  
DRUG:	 DROPERIDOL  
DRUG:	 BUPROPION  
DRUG:	 CINACALCET  
HEADER	
HEADER	
HEADER	
HEADER	#### Tegafur %%%%
DRUG:	 COUMARINS 
DRUG:	 CLOZAPINE  
DRUG:	 FOLIC ACID 
HEADER	#### Teicoplanin %%%%
HEADER	#### Telaprevir %%%%
DRUG:	 ALFUZOSIN 
DRUG:	 METHADONE  
DRUG:	 LIDOCAINE 
DRUG:	 CLARITHROMYCIN 
DRUG:	 RIFABUTIN 
DRUG:	 RIFAMPICIN 
DRUG:	 DABIGATRAN 
DRUG:	 PRIMIDONE 
DRUG:	 VORICONAZOLE  
DRUG:	 QUETIAPINE 
DRUG:	 TIPRANAVIR 
DRUG:	 MIDAZOLAM  
DRUG:	 SOTALOL  
DRUG:	 CICLOSPORIN  
DRUG:	 CILOSTAZOL  
DRUG:	 COLCHICINE  
DRUG:	 RUXOLITINIB 
DRUG:	 DOMPERIDONE 
DRUG:	 ERGOT ALKALOIDS 
DRUG:	 ATORVASTATIN 
DRUG:	 LOMITAPIDE  
DRUG:	 ETHINYLESTRADIOL 
DRUG:	 SILDENAFIL 
DRUG:	 SIROLIMUS  
DRUG:	 SALMETEROL  
DRUG:	 TACROLIMUS  
DRUG:	 TADALAFIL 
DRUG:	 VARDENAFIL 
HEADER	#### Telavancin %%%%
HEADER	#### Telbivudine %%%%
DRUG:	 INTERFERON ALFA  
DRUG:	 PEGINTERFERON ALFA 
HEADER	#### Telithromycin %%%%
DRUG:	 OXYCODONE 
DRUG:	 DRONEDARONE 
DRUG:	 MOXIFLOXACIN 
DRUG:	 RIFAMPICIN  
DRUG:	 PHENOBARBITAL 
DRUG:	 PRIMIDONE  
DRUG:	 KETOCONAZOLE 
DRUG:	 QUETIAPINE 
DRUG:	 FOSAMPRENAVIR 
DRUG:	 TIPRANAVIR  
DRUG:	 DACLATASVIR 
HEADER	#### Telithromycin %%%%
DRUG:	 MARAVIROC  
DRUG:	 SAQUINAVIR  
DRUG:	 SIMEPREVIR 
DRUG:	 TELAPREVIR  
DRUG:	 MIDAZOLAM  
DRUG:	 AVANAFIL 
DRUG:	 CALCIUM-CHANNEL BLOCKERS  
DRUG:	 CICLOSPORIN 
DRUG:	 COLCHICINE  
DRUG:	 CABAZITAXEL 
DRUG:	 IBRUTINIB 
DRUG:	 RUXOLITINIB 
DRUG:	 DOCETAXEL 
DRUG:	 DAPOXETINE  
DRUG:	 EPLERENONE 
DRUG:	 DOMPERIDONE 
DRUG:	 ERGOTAMINE 
DRUG:	 IVABRADINE 
DRUG:	 IVACAFTOR  
DRUG:	 LOMITAPIDE  
DRUG:	 PENTAMIDINE ISETIONATE 
DRUG:	 RANOLAZINE 
DRUG:	 SILDENAFIL 
DRUG:	 SIROLIMUS 
DRUG:	 TACROLIMUS 
HEADER	
HEADER	
HEADER	
HEADER	#### Temoporfin %%%%
DRUG:	 FLUOROURACIL 
HEADER	#### Temozolomide %%%%
DRUG:	 CLOZAPINE  
HEADER	#### Temsirolimus %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 ITRACONAZOLE  
DRUG:	 CLOZAPINE  
HEADER	#### Tenofovir %%%%
DRUG:	 TELAPREVIR 
DRUG:	 ORLISTAT 
HEADER	#### Terbinafine %%%%
DRUG:	 RIFAMPICIN 
HEADER	
HEADER	#### Teriflunomide %%%%
DRUG:	 COLESTYRAMINE  
DRUG:	 ROSUVASTATIN  
DRUG:	 VACCINES 
HEADER	#### Testolactone %%%%
DRUG:	 PHENINDIONE 
HEADER	#### Testosterone %%%%
DRUG:	 PHENINDIONE 
HEADER	#### Tetrabenazine %%%%
DRUG:	 MAOIS  
HEADER	#### Tetracyclines %%%%
DRUG:	 PHENINDIONE 
DRUG:	 RETINOIDS  
HEADER	#### Theophylline %%%%
DRUG:	 QUINOLONES 
DRUG:	 PRIMIDONE  
DRUG:	 PHENYTOIN 
DRUG:	 KETOCONAZOLE 
DRUG:	 RITONAVIR  
DRUG:	 VERAPAMIL  
DRUG:	 DEFERASIROX  
DRUG:	 PEGINTERFERON ALFA  
DRUG:	 SUCRALFATE  
HEADER	#### Thiotepa %%%%
DRUG:	 CLOZAPINE  
HEADER	
HEADER	#### Thyroid Hormones %%%%
DRUG:	 PHENINDIONE 
HEADER	#### Tiagabine %%%%
DRUG:	 TRICYCLIC-RELATED 
HEADER	#### Tiagabine %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	
HEADER	#### Tibolone %%%%
HEADER	#### Ticagrelor %%%%
DRUG:	 RIFAMPICIN 
DRUG:	 DABIGATRAN 
DRUG:	 KETOCONAZOLE 
DRUG:	 RITONAVIR 
DRUG:	 DIGOXIN 
DRUG:	 ERGOT ALKALOIDS 
DRUG:	 LOMITAPIDE 
HEADER	
HEADER	
HEADER	#### Tigecycline %%%%
HEADER	
HEADER	#### Tinidazole %%%%
HEADER	
HEADER	#### Tioguanine %%%%
DRUG:	 CLOZAPINE  
HEADER	
HEADER	#### Tipranavir %%%%
DRUG:	 RIFABUTIN  
DRUG:	 TELITHROMYCIN 
DRUG:	 QUININE  
DRUG:	 ARIPIPRAZOLE  
DRUG:	 QUETIAPINE 
DRUG:	 SAQUINAVIR  
DRUG:	 ETRAVIRINE 
DRUG:	 METOPROLOL  
DRUG:	 COBICISTAT  
DRUG:	 ATORVASTATIN  
DRUG:	 SIMVASTATIN 
DRUG:	 LOMITAPIDE  
DRUG:	 ORLISTAT 
DRUG:	 RANOLAZINE 
DRUG:	 OMEPRAZOLE 
HEADER	#### Tirofiban %%%%
HEADER	#### Tocilizumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Tolcapone %%%%
HEADER	#### Tolvaptan %%%%
DRUG:	 GRAPEFRUIT JUICE 
HEADER	#### Topiramate %%%%
DRUG:	 TRICYCLICS  
DRUG:	 VALPROIC ACID 
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 OESTROGENS  
DRUG:	 ORLISTAT 
DRUG:	 PROGESTOGENS  
HEADER	
HEADER	#### Toremifene %%%%
DRUG:	 COUMARINS 
DRUG:	 VANDETANIB 
HEADER	#### Trabectedin %%%%
DRUG:	 ALCOHOL 
DRUG:	 RIFAMPICIN 
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Trastuzumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	
HEADER	#### Trientine %%%%
HEADER	#### Trimethoprim %%%%
DRUG:	 PHENYTOIN  
DRUG:	 PYRIMETHAMINE 
DRUG:	 AZATHIOPRINE 
DRUG:	 CICLOSPORIN 
DRUG:	 METHOTREXATE 
HEADER	
HEADER	#### Tripotassium Dicitratobismuthate %%%%
HEADER	
HEADER	
HEADER	#### Ubidecarenone %%%%
HEADER	
HEADER	#### Ulipristal %%%%
DRUG:	 RIFAMPICIN  
DRUG:	 PRIMIDONE 
DRUG:	 RITONAVIR  
DRUG:	 PROGESTOGENS 
HEADER	#### Ustekinumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Vaccines %%%%
DRUG:	 ABATACEPT 
DRUG:	 ANAKINRA 
DRUG:	 CORTICOSTEROIDS 
DRUG:	 MONOCLONAL ANTIBODIES 
DRUG:	 TRABECTEDIN 
DRUG:	 DEXRAZOXANE 
DRUG:	 ETANERCEPT 
DRUG:	 NORMAL IMMUNOGLOBULIN 
DRUG:	 NORMAL IMMUNOGLOBULIN 
DRUG:	 NORMAL IMMUNOGLOBULIN 
DRUG:	 LEFLUNOMIDE 
DRUG:	 TERIFLUNOMIDE 
HEADER	#### Valaciclovir %%%%
HEADER	#### Valganciclovir %%%%
DRUG:	 IMIPENEM WITH CILASTATIN 
DRUG:	 ZIDOVUDINE  
HEADER	#### Valganciclovir %%%%
HEADER	#### Valproic Acid %%%%
DRUG:	 CARBAPENEMS 
DRUG:	 TRICYCLICS  
DRUG:	 TOPIRAMATE 
DRUG:	 MEFLOQUINE 
DRUG:	 OLANZAPINE 
DRUG:	 ORLISTAT 
DRUG:	 SODIUM OXYBATE  
DRUG:	 Vancomycin 
DRUG:	 POLYMYXINS 
DRUG:	 CICLOSPORIN 
DRUG:	 LOOP DIURETICS 
DRUG:	 SUXAMETHONIUM 
HEADER	#### Vandetanib %%%%
DRUG:	 METHADONE 
DRUG:	 DISOPYRAMIDE 
DRUG:	 RIFAMPICIN 
DRUG:	 MIZOLASTINE 
DRUG:	 ARTEMETHER WITH LUMEFANTRINE 
DRUG:	 AMISULPRIDE 
DRUG:	 SULPIRIDE  
DRUG:	 CLOZAPINE  
DRUG:	 SOTALOL 
DRUG:	 ARSENIC TRIOXIDE 
DRUG:	 TOREMIFENE 
DRUG:	 ONDANSETRON 
DRUG:	 PENTAMIDINE ISETIONATE 
HEADER	#### Vardenafil %%%%
DRUG:	 ALPHA-BLOCKERS 
DRUG:	 KETOCONAZOLE 
DRUG:	 ITRACONAZOLE 
DRUG:	 SAQUINAVIR 
DRUG:	 TIPRANAVIR 
DRUG:	 COBICISTAT 
DRUG:	 GRAPEFRUIT JUICE 
DRUG:	 NICORANDIL 
DRUG:	 NITRATES 
DRUG:	 RIOCIGUAT 
HEADER	
HEADER	#### Vasodilator Antihypertensives %%%%
HEADER	
HEADER	#### Vedolizumab %%%%
DRUG:	 CLOZAPINE  
DRUG:	 VACCINES 
HEADER	#### Vemurafenib %%%%
DRUG:	 WARFARIN 
DRUG:	 CLOZAPINE  
DRUG:	 OESTROGENS  
DRUG:	 PROGESTOGENS  
HEADER	#### Venlafaxine %%%%
DRUG:	 TRAMADOL 
DRUG:	 DABIGATRAN 
DRUG:	 MOCLOBEMIDE  
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 DAPOXETINE  
DRUG:	 SELEGILINE  
DRUG:	 METHYLTHIONINIUM 
HEADER	
HEADER	#### Vigabatrin %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	#### Vinblastine %%%%
DRUG:	 ALDESLEUKIN 
DRUG:	 DELAMANID 
DRUG:	 POSACONAZOLE  
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 CLOZAPINE  
HEADER	#### Vincristine %%%%
DRUG:	 DELAMANID 
DRUG:	 POSACONAZOLE  
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 CLOZAPINE  
HEADER	#### Vindesine %%%%
DRUG:	 DELAMANID 
DRUG:	 ITRACONAZOLE 
DRUG:	 CLOZAPINE  
HEADER	#### Vinflunine %%%%
DRUG:	 DELAMANID 
DRUG:	 ITRACONAZOLE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 CLOZAPINE  
DRUG:	 RITONAVIR 
HEADER	#### Vinorelbine %%%%
DRUG:	 DELAMANID 
DRUG:	 ITRACONAZOLE 
DRUG:	 ARTENIMOL WITH PIPERAQUINE 
DRUG:	 CLOZAPINE  
HEADER	#### Vismodegib %%%%
DRUG:	 RIFAMPICIN  
DRUG:	 PHENYTOIN  
DRUG:	 CLOZAPINE  
HEADER	
HEADER	
HEADER	#### Vitamins %%%%
DRUG:	 PHENINDIONE 
DRUG:	 RETINOIDS 
HEADER	
HEADER	
HEADER	#### Wasp Venom Extracts %%%%
DRUG:	 ACE INHIBITORS 
HEADER	
HEADER	
HEADER	
HEADER	#### Zidovudine %%%%
DRUG:	 FLUCONAZOLE  
DRUG:	 NEVIRAPINE 
DRUG:	 TIPRANAVIR 
DRUG:	 ORLISTAT 
HEADER	#### Zinc %%%%
HEADER	
HEADER	
HEADER	
HEADER	#### Zonisamide %%%%
DRUG:	 TRICYCLICS  
DRUG:	 MEFLOQUINE 
DRUG:	 ANTIPSYCHOTICS  
DRUG:	 ORLISTAT 
HEADER	
HEADER	
Binary file (standard input) matches
